This is a temporary script with exploration of data for 2022 year to decide whether it is worth to create tables, charts, and maps for this year.

Data sources: [US Mortality DataBase](https://usa.mortality.org) / [U.S State Life Tables CSV + TXT 1941-2022](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/19WYUX)<br>
[List of U.S. states and territories by life expectancy](https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_life_expectancy) <i>([alternative](https://en.wikipedia.org/wiki/User:Lady3mlnm/List_of_U.S._states_and_territories_by_life_expectancy_(alternative)))</i> / [Продолжительность жизни в штатах США](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_штатах_США)<br>
[MapChart](https://www.mapchart.net/usa.html)<br>
<br>
For small exploration: american presidents:<br>
Barack Obama: 2009–2016<br>
Donald Trump: 2017-2020<br>
Joe Biden: 2021-2024<br>
[results of the 2024 US presidential election](https://en.wikipedia.org/wiki/2024_United_States_presidential_election#Results)

In [3]:
import pandas as pd
from collections import namedtuple
from itertools import product
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [4]:
pd.options.display.min_rows=4
pd.options.display.max_columns = 30

In [5]:
YEARS=[2014, 2018, 2019, 2020, 2021, 2022]

In [6]:
StateInfo = namedtuple('StateInfo', ['en_name', 'en_page', 'ru_name', 'ru_page'])

In [7]:
dd_states = {
    'AL': StateInfo('Alabama', 'Alabama', 'Алаба́ма', 'Алабама'),
    'AK': StateInfo('Alaska', 'Alaska', 'Аля́ска', 'Аляска'),
    'AZ': StateInfo('Arizona', 'Arizona', 'Аризо́на', 'Аризона'),
    'AR': StateInfo('Arkansas', 'Arkansas', 'Арканза́с (Арка́нзас)', 'Арканзас'),
    'CA': StateInfo('California', 'California', 'Калифо́рния', 'Калифорния'),
    'CO': StateInfo('Colorado', 'Colorado', 'Колора́до', 'Колорадо'),
    'CT': StateInfo('Connecticut', 'Connecticut', 'Конне́ктикут', 'Коннектикут'),
    'DE': StateInfo('Delaware', 'Delaware', 'Де́лавэр', 'Делавэр'),
    'DC': StateInfo('Washington, D.C.', 'Washington, D.C.', 'Вашингто́н (Ва́шингтон)', 'Вашингтон'),
    'FL': StateInfo('Florida', 'Florida', 'Флори́да', 'Флорида'),
    'GA': StateInfo('Georgia', 'Georgia (U.S. state)', 'Джо́рджия', 'Джорджия'),
    'HI': StateInfo('Hawaii', 'Hawaii', 'Гава́йи', 'Гавайи'),
    'ID': StateInfo('Idaho', 'Idaho', 'Айда́хо (А́йдахо)', 'Айдахо'),
    'IL': StateInfo('Illinois', 'Illinois', 'Иллино́йс', 'Иллинойс'),
    'IN': StateInfo('Indiana', 'Indiana', 'Индиа́на', 'Индиана'),
    'IA': StateInfo('Iowa', 'Iowa', 'А́йова (Айо́ва)', 'Айова'),
    'KS': StateInfo('Kansas', 'Kansas', 'Ка́нзас (Канза́с)', 'Канзас'),
    'KY': StateInfo('Kentucky', 'Kentucky', 'Кенту́кки', 'Кентукки'),
    'LA': StateInfo('Louisiana', 'Louisiana', 'Луизиа́на', 'Луизиана'),
    'ME': StateInfo('Maine', 'Maine', 'Мэн', 'Мэн (штат)'),
    'MD': StateInfo('Maryland', 'Maryland', 'Мэ́риленд', 'Мэриленд'),
    'MA': StateInfo('Massachusetts', 'Massachusetts', 'Массачу́сетс', 'Массачусетс'),
    'MI': StateInfo('Michigan', 'Michigan', 'Мичига́н', 'Мичиган'),
    'MN': StateInfo('Minnesota', 'Minnesota', 'Миннесо́та', 'Миннесота'),
    'MS': StateInfo('Mississippi', 'Mississippi', 'Миссиси́пи', 'Миссисипи (штат)'),
    'MO': StateInfo('Missouri', 'Missouri', 'Миссу́ри', 'Миссури (штат)'),
    'MT': StateInfo('Montana', 'Montana', 'Монта́на', 'Монтана'),
    'NE': StateInfo('Nebraska', 'Nebraska', 'Небра́ска', 'Небраска'),
    'NV': StateInfo('Nevada', 'Nevada', 'Нева́да', 'Невада'),
    'NH': StateInfo('New Hampshire', 'New Hampshire', 'Нью-Гэ́мпшир', 'Нью-Гэмпшир'),
    'NJ': StateInfo('New Jersey', 'New Jersey', 'Нью-Дже́рси', 'Нью-Джерси'),
    'NM': StateInfo('New Mexico', 'New Mexico', 'Нью-Ме́ксико', 'Нью-Мексико'),
    'NY': StateInfo('New York', 'New York (state)', 'Нью-Йо́рк (штат)', 'Нью-Йорк (штат)'),
    'NC': StateInfo('North Carolina', 'North Carolina', 'Северная Кароли́на', 'Северная Каролина'),
    'ND': StateInfo('North Dakota', 'North Dakota', 'Северная Дако́та', 'Северная Дакота'),
    'OH': StateInfo('Ohio', 'Ohio', 'Ога́йо', 'Огайо'),
    'OK': StateInfo('Oklahoma', 'Oklahoma', 'Оклахо́ма', 'Оклахома'),
    'OR': StateInfo('Oregon', 'Oregon', 'Орего́н', 'Орегон'),
    'PA': StateInfo('Pennsylvania', 'Pennsylvania', 'Пенсильва́ния', 'Пенсильвания'),
    'RI': StateInfo('Rhode Island', 'Rhode Island', 'Род-А́йленд', 'Род-Айленд'),
    'SC': StateInfo('South Carolina', 'South Carolina', 'Южная Кароли́на', 'Южная Каролина'),
    'SD': StateInfo('South Dakota', 'South Dakota', 'Южная Дако́та', 'Южная Дакота'),
    'TN': StateInfo('Tennessee', 'Tennessee', 'Теннесси́', 'Теннесси'),
    'TX': StateInfo('Texas', 'Texas', 'Теха́с', 'Техас'),
    'UT': StateInfo('Utah', 'Utah', 'Ю́та', 'Юта'),
    'VT': StateInfo('Vermont', 'Vermont', 'Вермо́нт', 'Вермонт'),
    'VA': StateInfo('Virginia', 'Virginia', 'Вирги́ния (Вирджи́ния)', 'Виргиния'),
    'WA': StateInfo('Washington (state)', 'Washington (state)', 'Вашингто́н (штат)', 'Вашингтон (штат)'),
    'WV': StateInfo('West Virginia', 'West Virginia', 'Западная Вирги́ния', 'Западная Виргиния'),
    'WI': StateInfo('Wisconsin', 'Wisconsin', 'Виско́нсин', 'Висконсин'),
    'WY': StateInfo('Wyoming', 'Wyoming', 'Вайо́минг', 'Вайоминг')
}

In [8]:
def load_data_single_unit(abbr, name, years, level='States'):
    '''
    The function loads data from disk and constructs dataframe for a separate state or the whole country
    depending on the value of variable 'level'.
    The dataframe contains a single record with life expectancy for given years
    for total population, male, female, and also sex gap between female and male.
    '''
    df_t = pd.read_csv(f"data/{level}/{abbr}/{abbr}_bltper_1x1.csv", sep=',', usecols=['Year', 'Age', 'ex'])
    df_t = df_t.loc[(df_t['Year'].isin(years)) & (df_t['Age'] == '0')] \
               .drop(columns='Age') \
               .set_index('Year') \
               .transpose() \

    df_m = pd.read_csv(f"data/{level}/{abbr}/{abbr}_mltper_1x1.csv", sep=',', usecols=['Year', 'Age', 'ex'])
    df_m = df_m.loc[(df_m['Year'].isin(years)) & (df_m['Age'] == '0')] \
               .drop(columns='Age') \
               .set_index('Year') \
               .transpose() \

    df_f = pd.read_csv(f"data/{level}/{abbr}/{abbr}_fltper_1x1.csv", sep=',', usecols=['Year', 'Age', 'ex'])
    df_f = df_f.loc[(df_f['Year'].isin(years)) & (df_f['Age'] == '0')] \
               .drop(columns='Age') \
               .set_index('Year') \
               .transpose() \

    df = pd.concat([tp[1][tp[0]] for tp in product(years, [df_t, df_m, df_f])],
                   axis='columns')

    df.columns = [f"{tp[0]}_{tp[1]}" for tp in product(years, ['t', 'm', 'f'])]

    # for i, year in enumerate(years):
    #     df.insert(loc=i*4+3, column=f'{year}_fΔm', value=(df[f'{year}_f']-df[f'{year}_m']).round(2))

    df.index = [name]

    return df

# test with a single state
# df = load_data_state('CA', 'California', YEARS)
# df

<br>

In [10]:
# load data for all states
df = pd.concat(load_data_single_unit(abbr, dd.en_name, YEARS) for abbr, dd in dd_states.items())

In [11]:
# combine data for states with data for the whole country
df_country = load_data_single_unit('USA', '– US –', YEARS, level='Nationals')

df = pd.concat([df_country, df.sort_values(by=['2019_t', '2019_m', '2019_f'], ascending=False)])
df.head()

,2014_t,2014_m,2014_f,2018_t,2018_m,2018_f,2019_t,2019_m,2019_f,2020_t,2020_m,2020_f,2021_t,2021_m,2021_f,2022_t,2022_m,2022_f
– US –,78.89,76.46,81.25,78.78,76.26,81.28,78.91,76.40,81.43,77.05,74.32,79.88,76.45,73.63,79.41,77.54,74.88,80.28
Hawaii,81.46,78.63,84.19,81.62,78.64,84.60,81.60,78.63,84.60,81.64,78.60,84.71,80.89,77.85,84.10,80.88,77.86,84.06
California,81.04,78.73,83.26,81.02,78.62,83.40,81.15,78.69,83.60,79.24,76.44,82.16,78.58,75.59,81.74,79.72,76.99,82.55
New York,80.69,78.27,82.90,80.83,78.39,83.10,81.06,78.54,83.43,78.25,75.32,81.19,79.43,76.68,82.12,80.08,77.36,82.73
Minnesota,80.90,78.84,82.89,80.73,78.56,82.88,80.67,78.45,82.90,79.29,77.03,81.62,78.99,76.45,81.65,79.42,77.13,81.80

<br>

In [13]:
# just for interest, explore results: determine regions with max and min values, and also look at specific regions
mal.min_and_max_values(df[['2014_t', '2018_t', '2019_t', '2020_t', '2021_t', '2022_t']],
                       row_center=['– US –'], nmb=5, max_lng=13)

Number of records: 52

<br>

In [15]:
# Calculate changes
df.insert(loc=3, column='2014→2018', value=(df['2018_t']-df['2014_t']).round(2))
df.insert(loc=7, column='2018→2019', value=(df['2019_t']-df['2018_t']).round(2))
df.insert(loc=11, column='2019→2020', value=(df['2020_t']-df['2019_t']).round(2))
df.insert(loc=15, column='2020→2021', value=(df['2021_t']-df['2020_t']).round(2))
df.insert(loc=19, column='2021→2022', value=(df['2022_t']-df['2021_t']).round(2))
df.head()

,2014_t,2014_m,2014_f,2014→2018,2018_t,2018_m,2018_f,2018→2019,2019_t,2019_m,2019_f,2019→2020,2020_t,2020_m,2020_f,2020→2021,2021_t,2021_m,2021_f,2021→2022,2022_t,2022_m,2022_f
– US –,78.89,76.46,81.25,-0.11,78.78,76.26,81.28,0.13,78.91,76.40,81.43,-1.86,77.05,74.32,79.88,-0.60,76.45,73.63,79.41,1.09,77.54,74.88,80.28
Hawaii,81.46,78.63,84.19,0.16,81.62,78.64,84.60,-0.02,81.60,78.63,84.60,0.04,81.64,78.60,84.71,-0.75,80.89,77.85,84.10,-0.01,80.88,77.86,84.06
California,81.04,78.73,83.26,-0.02,81.02,78.62,83.40,0.13,81.15,78.69,83.60,-1.91,79.24,76.44,82.16,-0.66,78.58,75.59,81.74,1.14,79.72,76.99,82.55
New York,80.69,78.27,82.90,0.14,80.83,78.39,83.10,0.23,81.06,78.54,83.43,-2.81,78.25,75.32,81.19,1.18,79.43,76.68,82.12,0.65,80.08,77.36,82.73
Minnesota,80.90,78.84,82.89,-0.17,80.73,78.56,82.88,-0.06,80.67,78.45,82.90,-1.38,79.29,77.03,81.62,-0.30,78.99,76.45,81.65,0.43,79.42,77.13,81.80

In [16]:
mal.min_and_max_values(df[['2014_t', '2014→2018', '2018_t', '2018→2019', '2019_t', '2019→2020', '2020_t', '2020→2021', '2021_t', '2021→2022', '2022_t']],
                       row_center=['– US –'], nmb=5, max_lng=13)

Number of records: 52

<br>
<br>
<br>

In [18]:
# dd_replacement = {
#     'AL': {'en': ('Alabama', 'Alabama'), 'ru': ('Алаба́ма', 'Алабама')},
#     'AK': {'en': ('Alaska', 'Alaska'), 'ru': ('Аля́ска', 'Аляска')},
#     'AZ': {'en': ('Arizona', 'Arizona'), 'ru': ('Аризо́на', 'Аризона')},
#     'AR': {'en': ('Arkansas', 'Arkansas'), 'ru': ('Арканза́с (Арка́нзас)', 'Арканзас')},
#     'CA': {'en': ('California', 'California'), 'ru': ('Калифо́рния', 'Калифорния')},
#     'CO': {'en': ('Colorado', 'Colorado'), 'ru': ('Колора́до', 'Колорадо')},
#     'CT': {'en': ('Connecticut', 'Connecticut'), 'ru': ('Конне́ктикут', 'Коннектикут')},
#     'DE': {'en': ('Delaware', 'Delaware'), 'ru': ('Де́лавэр', 'Делавэр')},
#     'DC': {'en': ('Washington, D.C.', 'Washington, D.C.'), 'ru': ('Вашингто́н (Ва́шингтон)', 'Вашингтон')},
#     'FL': {'en': ('Florida', 'Florida'), 'ru': ('Флори́да', 'Флорида')},
#     'GA': {'en': ('Georgia', 'Georgia (U.S. state)'), 'ru': ('Джо́рджия', 'Джорджия')},
#     'HI': {'en': ('Hawaii', 'Hawaii'), 'ru': ('Гава́йи', 'Гавайи')},
#     'ID': {'en': ('Idaho', 'Idaho'), 'ru': ('Айда́хо (А́йдахо)', 'Айдахо')},
#     'IL': {'en': ('Illinois', 'Illinois'), 'ru': ('Иллино́йс', 'Иллинойс')},
#     'IN': {'en': ('Indiana', 'Indiana'), 'ru': ('Индиа́на', 'Индиана')},
#     'IA': {'en': ('Iowa', 'Iowa'), 'ru': ('А́йова (Айо́ва)', 'Айова')},
#     'KS': {'en': ('Kansas', 'Kansas'), 'ru': ('Ка́нзас (Канза́с)', 'Канзас')},
#     'KY': {'en': ('Kentucky', 'Kentucky'), 'ru': ('Кенту́кки', 'Кентукки')},
#     'LA': {'en': ('Louisiana', 'Louisiana'), 'ru': ('Луизиа́на', 'Луизиана')},
#     'ME': {'en': ('Maine', 'Maine'), 'ru': ('Мэн', 'Мэн (штат)')},
#     'MD': {'en': ('Maryland', 'Maryland'), 'ru': ('Мэ́риленд', 'Мэриленд')},
#     'MA': {'en': ('Massachusetts', 'Massachusetts'), 'ru': ('Массачу́сетс', 'Массачусетс')},
#     'MI': {'en': ('Michigan', 'Michigan'), 'ru': ('Мичига́н', 'Мичиган')},
#     'MN': {'en': ('Minnesota', 'Minnesota'), 'ru': ('Миннесо́та', 'Миннесота')},
#     'MS': {'en': ('Mississippi', 'Mississippi'), 'ru': ('Миссиси́пи', 'Миссисипи (штат)')},
#     'MO': {'en': ('Missouri', 'Missouri'), 'ru': ('Миссу́ри', 'Миссури (штат)')},
#     'MT': {'en': ('Montana', 'Montana'), 'ru': ('Монта́на', 'Монтана')},
#     'NE': {'en': ('Nebraska', 'Nebraska'), 'ru': ('Небра́ска', 'Небраска')},
#     'NV': {'en': ('Nevada', 'Nevada'), 'ru': ('Нева́да', 'Невада')},
#     'NH': {'en': ('New Hampshire', 'New Hampshire'), 'ru': ('Нью-Гэ́мпшир', 'Нью-Гэмпшир')},
#     'NJ': {'en': ('New Jersey', 'New Jersey'), 'ru': ('Нью-Дже́рси', 'Нью-Джерси')},
#     'NM': {'en': ('New Mexico', 'New Mexico'), 'ru': ('Нью-Ме́ксико', 'Нью-Мексико')},
#     'NY': {'en': ('New York', 'New York (state)'), 'ru': ('Нью-Йо́рк (штат)', 'Нью-Йорк (штат)')},
#     'NC': {'en': ('North Carolina', 'North Carolina'), 'ru': ('Северная Кароли́на', 'Северная Каролина')},
#     'ND': {'en': ('North Dakota', 'North Dakota'), 'ru': ('Северная Дако́та', 'Северная Дакота')},
#     'OH': {'en': ('Ohio', 'Ohio'), 'ru': ('Ога́йо', 'Огайо')},
#     'OK': {'en': ('Oklahoma', 'Oklahoma'), 'ru': ('Оклахо́ма', 'Оклахома')},
#     'OR': {'en': ('Oregon', 'Oregon'), 'ru': ('Орего́н', 'Орегон')},
#     'PA': {'en': ('Pennsylvania', 'Pennsylvania'), 'ru': ('Пенсильва́ния', 'Пенсильвания')},
#     'RI': {'en': ('Rhode Island', 'Rhode Island'), 'ru': ('Род-А́йленд', 'Род-Айленд')},
#     'SC': {'en': ('South Carolina', 'South Carolina'), 'ru': ('Южная Кароли́на', 'Южная Каролина')},
#     'SD': {'en': ('South Dakota', 'South Dakota'), 'ru': ('Южная Дако́та', 'Южная Дакота')},
#     'TN': {'en': ('Tennessee', 'Tennessee'), 'ru': ('Теннесси́', 'Теннесси')},
#     'TX': {'en': ('Texas', 'Texas'), 'ru': ('Теха́с', 'Техас')},
#     'UT': {'en': ('Utah', 'Utah'), 'ru': ('Ю́та', 'Юта')},
#     'VT': {'en': ('Vermont', 'Vermont'), 'ru': ('Вермо́нт', 'Вермонт')},
#     'VA': {'en': ('Virginia', 'Virginia'), 'ru': ('Вирги́ния (Вирджи́ния)', 'Виргиния')},
#     'WA': {'en': ('Washington (state)', 'Washington (state)'), 'ru': ('Вашингто́н (штат)', 'Вашингтон (штат)')},
#     'WV': {'en': ('West Virginia', 'West Virginia'), 'ru': ('Западная Вирги́ния', 'Западная Виргиния')},
#     'WI': {'en': ('Wisconsin', 'Wisconsin'), 'ru': ('Виско́нсин', 'Висконсин')},
#     'WY': {'en': ('Wyoming', 'Wyoming'), 'ru': ('Вайо́минг', 'Вайоминг')}
# }

# for abbr, dd in dd_replacement.items():
#     print(f"    '{abbr}': StateInfo('{dd['en'][0]}', '{dd['en'][1]}', '{dd['ru'][0]}', '{dd['ru'][1]}'),")