source of data: [Instituto Nacional de Estadística: Provinces](https://www.ine.es/jaxiT3/Tabla.htm?t=1485&L=1),<br>
Spain as a whole: [Total](https://www.ine.es/consul/serie.do?d=true&s=TM2177),
[Males](https://www.ine.es/consul/serie.do?d=true&s=TM1449),
[Females](https://www.ine.es/consul/serie.do?d=true&s=TM721)<br>
wiki > [List of Spanish provinces by life expectancy](https://en.wikipedia.org/wiki/List_of_Spanish_provinces_by_life_expectancy) <i>([alternative](https://en.wikipedia.org/wiki/User:Lady3mlnm/List_of_Spanish_provinces_by_life_expectancy_(alternative)))</i>, [Political divisions of Spain](https://en.wikipedia.org/wiki/Political_divisions_of_Spain), [Provinces of Spain](https://en.wikipedia.org/wiki/Provinces_of_Spain)<br>
wiki > [Продолжительность жизни в провинциях Испании](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_провинциях_Испании), [Административное деление Испании](https://ru.wikipedia.org/wiki/Административное_деление_Испании), [Провинции Испании](https://ru.wikipedia.org/wiki/Провинции_Испании)<br />

In [2]:
import pandas as pd
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [3]:
pd.options.display.max_columns = 30

docs: [standard-encodings](https://docs.python.org/3/library/codecs.html#standard-encodings)<br>
docs: [docs: error-handlers](https://docs.python.org/3/library/codecs.html#error-handlers)

In [5]:
# load stats about longevity per year
df = pd.read_csv('data/Life expectancy in Spain.csv', sep='\t', encoding='mbcs')  # encoding_errors='replace' ascii

df.head(2)

     Provinces           Sex  Period  Total
0  02 Albacete  Both genders    2024  83.66
1  02 Albacete  Both genders    2023  83.61

In [6]:
# remove numbers before provinces names
df['Provinces'] = df['Provinces'].map(lambda st:st[3:])

# set provinces names as index
df.set_index('Provinces', drop=True, inplace=True)
df.index.name = ''

df.head(10)

                   Sex  Period  Total

Albacete  Both genders    2024  83.66
Albacete  Both genders    2023  83.61
Albacete  Both genders    2022  82.99
Albacete  Both genders    2021  83.21
Albacete  Both genders    2020  81.36
Albacete  Both genders    2019  83.31
Albacete  Both genders    2018  83.36
Albacete  Both genders    2017  83.47
Albacete  Both genders    2016  83.14
Albacete  Both genders    2015  82.87

In [7]:
df = pd.concat([df[(df.Sex == 'Both genders') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2020)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2021)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2022)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2023)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2024)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2024)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2024)].Total
               ],
                  axis='columns',
                  keys=['2014', '2019', '2020', '2021', '2022', '2023', '2024', 'm_2014', 'm_2019', 'm_2024', 'f_2014', 'f_2019', 'f_2024'])

df.sort_values(by=['2024', 'm_2024'], ascending=False, inplace=True)

print(len(df))
df.head()

52

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Salamanca,84.58,84.69,82.53,84.73,84.12,85.40,85.77,81.75,82.02,83.46,87.38,87.34,87.99
Madrid,84.20,84.93,82.27,84.56,84.76,85.39,85.58,81.44,82.33,83.07,86.59,87.19,87.74
Segovia,84.09,84.70,81.49,84.06,84.41,83.92,85.30,81.29,82.34,82.78,87.06,87.08,87.84
Valladolid,83.86,84.62,82.92,83.96,84.09,84.72,85.02,81.23,82.17,82.48,86.36,86.95,87.45
Araba/Álava,84.38,84.76,83.59,84.31,84.13,85.07,85.02,81.76,81.80,82.43,86.87,87.71,87.54

<br />
<br />

Add data about Spain as a whole ([all](https://www.ine.es/consul/serie.do?d=true&s=TM2177), [male](https://www.ine.es/consul/serie.do?d=true&s=TM1449), [female](https://www.ine.es/consul/serie.do?d=true&s=TM721))

In [9]:
df_country_all = pd.read_csv('data/Life expectancy in Spain as a whole -all.csv', sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD')
df_country_male = pd.read_csv('data/Life expectancy in Spain as a whole -male.csv', sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD')
df_country_female = pd.read_csv('data/Life expectancy in Spain as a whole -female.csv', sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD')

In [10]:
df_country = pd.DataFrame({'2014'  : [df_country_all.loc[2014, 'VALUE']],
                           '2019'  : [df_country_all.loc[2019, 'VALUE']],
                           '2020'  : [df_country_all.loc[2020, 'VALUE']],
                           '2021'  : [df_country_all.loc[2021, 'VALUE']],
                           '2022'  : [df_country_all.loc[2022, 'VALUE']],
                           '2023'  : [df_country_all.loc[2023, 'VALUE']],
                           '2024'  : [df_country_all.loc[2024, 'VALUE']],
                           'm_2014': [df_country_male.loc[2014, 'VALUE']],
                           'm_2019': [df_country_male.loc[2019, 'VALUE']],
                           'm_2024': [df_country_male.loc[2024, 'VALUE']],
                           'f_2014': [df_country_female.loc[2014, 'VALUE']],
                           'f_2019': [df_country_female.loc[2019, 'VALUE']],
                           'f_2024': [df_country_female.loc[2024, 'VALUE']],  
                          }, index=['Spain']).round(2)

df_country

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
Spain,82.91,83.53,82.28,83.03,83.08,83.77,84.01,80.1,80.78,81.38,85.63,86.19,86.53

In [11]:
df = pd.concat([df_country, df])

print(len(df))
df.head()

53

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
Spain,82.91,83.53,82.28,83.03,83.08,83.77,84.01,80.10,80.78,81.38,85.63,86.19,86.53
Salamanca,84.58,84.69,82.53,84.73,84.12,85.40,85.77,81.75,82.02,83.46,87.38,87.34,87.99
Madrid,84.20,84.93,82.27,84.56,84.76,85.39,85.58,81.44,82.33,83.07,86.59,87.19,87.74
Segovia,84.09,84.70,81.49,84.06,84.41,83.92,85.30,81.29,82.34,82.78,87.06,87.08,87.84
Valladolid,83.86,84.62,82.92,83.96,84.09,84.72,85.02,81.23,82.17,82.48,86.36,86.95,87.45

In [12]:
df.insert(loc=1,  column='2014→2019', value=df['2019']-df['2014'])
df.insert(loc=3,  column='2019→2020', value=df['2020']-df['2019'])
df.insert(loc=5,  column='2020→2021', value=df['2021']-df['2020'])
df.insert(loc=7,  column='2021→2022', value=df['2022']-df['2021'])
df.insert(loc=9,  column='2022→2023', value=df['2023']-df['2022'])
df.insert(loc=11,  column='2023→2024', value=df['2024']-df['2023'])
df.insert(loc=13, column='2019→2024', value=df['2024']-df['2019'])
df.insert(loc=14, column='2014→2024', value=df['2024']-df['2014'])
df['f-m_2014'] = df['f_2014']-df['m_2014']
df['f-m_2019'] = df['f_2019']-df['m_2019']
df['f-m_2024'] = df['f_2024']-df['m_2024']

df.head()

,2014,2014→2019,2019,2019→2020,2020,2020→2021,2021,2021→2022,2022,2022→2023,2023,2023→2024,2024,2019→2024,2014→2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024,f-m_2014,f-m_2019,f-m_2024
Spain,82.91,0.62,83.53,-1.25,82.28,0.75,83.03,0.05,83.08,0.69,83.77,0.24,84.01,0.48,1.10,80.10,80.78,81.38,85.63,86.19,86.53,5.53,5.41,5.15
Salamanca,84.58,0.11,84.69,-2.16,82.53,2.20,84.73,-0.61,84.12,1.28,85.40,0.37,85.77,1.08,1.19,81.75,82.02,83.46,87.38,87.34,87.99,5.63,5.32,4.53
Madrid,84.20,0.73,84.93,-2.66,82.27,2.29,84.56,0.20,84.76,0.63,85.39,0.19,85.58,0.65,1.38,81.44,82.33,83.07,86.59,87.19,87.74,5.15,4.86,4.67
Segovia,84.09,0.61,84.70,-3.21,81.49,2.57,84.06,0.35,84.41,-0.49,83.92,1.38,85.30,0.60,1.21,81.29,82.34,82.78,87.06,87.08,87.84,5.77,4.74,5.06
Valladolid,83.86,0.76,84.62,-1.70,82.92,1.04,83.96,0.13,84.09,0.63,84.72,0.30,85.02,0.40,1.16,81.23,82.17,82.48,86.36,86.95,87.45,5.13,4.78,4.97

<br />
<br />

In [14]:
# just for interest, explore results: determine regions with max and min values, and also look at specific regions
mal.min_and_max_values(df[['2014', '2014→2019', '2019', '2019→2024', '2024', '2014→2024']],
                       row_center=['Spain'], nmb=(5, 3), max_lng=11, show_difference=True)   # .drop(['Ceuta', 'Melilla'])

Number of records: 53

In [15]:
mal.min_and_max_values(df[['m_2014', 'm_2019', 'm_2024', 'f_2014', 'f_2019', 'f_2024', 'f-m_2014', 'f-m_2019', 'f-m_2024']],
                       row_center=['Spain'], nmb=(5, 3), max_lng=11, show_difference=True)   # .drop(['Ceuta', 'Melilla'])

Number of records: 53

<br />
<br />

In [17]:
dd_replacement = {
    'Spain'   : {'es': ('España', ''), 'en': ('Spain on average', ''), 'ru': ('Испания в среднем', '')},
    'Albacete'   : {'es': ('Albacete', 'Provincia de Albacete'), 'en': ('Albacete', 'Province of Albacete'), 'ru': ('Альбасе́те ', 'Альбасете (провинция)')},
    'Alicante/Alacant'   : {'es': ('Alicante (Alacant)', 'Provincia de Alicante'), 'en': ('Alicante (Alacant)', 'Province of Alicante'), 'ru': ('Алика́нте (Алакант)', 'Аликанте (провинция)')},
    'Almería'   : {'es': ('Almería', 'Provincia de Almería'), 'en': ('Almería', 'Province of Almería'), 'ru': ('Альмери́я ', 'Альмерия (провинция)')},
    'Araba/Álava'   : {'es': ('Álava (Araba)', 'Álava'), 'en': ('Álava (Araba)', 'Álava'), 'ru': ('А́лава (Араба)', 'Алава')},
    'Asturias'   : {'es': ('Asturias', 'Asturias'), 'en': ('Asturias', 'Asturias'), 'ru': ('Асту́рия', 'Астурия')},
    'Badajoz'   : {'es': ('Badajoz', 'Provincia de Badajoz'), 'en': ('Badajoz', 'Province of Badajoz'), 'ru': ('Бадахо́с', 'Бадахос (провинция)')},
    'Balears, Illes'   : {'es': ('Islas Baleares', 'Islas Baleares'), 'en': ('Balearic Islands', 'Balearic Islands'), 'ru': ('Балеа́рские острова', 'Балеарские острова')},
    'Barcelona'   : {'es': ('Barcelona', 'Provincia de Barcelona'), 'en': ('Barcelona', 'Province of Barcelona'), 'ru': ('Барсело́на ', 'Барселона (провинция)')},
    'Bizkaia'   : {'es': ('Vizcaya (Bizkaia)', 'Vizcaya'), 'en': ('Biscay', 'Biscay'), 'ru': ('Биска́йя', 'Бискайя')},
    'Burgos'   : {'es': ('Burgos', 'Provincia de Burgos'), 'en': ('Burgos', 'Province of Burgos'), 'ru': ('Бу́ргос', 'Бургос (провинция)')},
    'Cantabria'   : {'es': ('Cantabria', 'Cantabria'), 'en': ('Cantabria', 'Cantabria'), 'ru': ('Канта́брия', 'Кантабрия')},
    'Castellón/Castelló'   : {'es': ('Castellón (Castelló)', 'Provincia de Castellón'), 'en': ('Castellón (Castelló)', 'Province of Castellón'), 'ru': ('Кастельо́н (Кастельо)', 'Кастельон (провинция)')},
    'Ceuta'   : {'es': ('Ceuta (ciudad autónoma)', 'Ceuta'), 'en': ('Ceuta (auton. city)', 'Ceuta'), 'ru': ('Сеу́та (автон. город)', 'Сеута')},
    'Ciudad Real'   : {'es': ('Ciudad Real', 'Provincia de Ciudad Real'), 'en': ('Ciudad Real', 'Province of Ciudad Real'), 'ru': ('Сьюда́д-Реа́ль', 'Сьюдад-Реаль (провинция)')},
    'Coruña, A'   : {'es': ('La Coruña', 'Provincia de La Coruña'), 'en': ('A Coruña', 'Province of A Coruña'), 'ru': ('Ла-Корунья', 'Ла-Корунья (провинция)')},
    'Cuenca'   : {'es': ('Cuenca', 'Provincia de Cuenca'), 'en': ('Cuenca', 'Province of Cuenca'), 'ru': ('Куэ́нка', 'Куэнка (провинция)')},
    'Cáceres'   : {'es': ('Cáceres', 'Provincia de Cáceres'), 'en': ('Cáceres', 'Province of Cáceres'), 'ru': ('Ка́серес', 'Касерес (провинция)')},
    'Cádiz'   : {'es': ('Cádiz', 'Provincia de Cádiz'), 'en': ('Cádiz', 'Province of Cádiz'), 'ru': ('Ка́дис', 'Кадис (провинция)')},
    'Córdoba'   : {'es': ('Córdoba', 'Provincia de Córdoba (España)'), 'en': ('Córdoba', 'Province of Córdoba (Spain)'), 'ru': ('Ко́рдова', 'Кордова (провинция, Испания)')},
    'Gipuzkoa'   : {'es': ('Guipúzcoa', 'Guipúzcoa'), 'en': ('Gipuzkoa', 'Gipuzkoa'), 'ru': ('Гипу́скоа', 'Гипускоа')},
    'Girona'   : {'es': ('Gerona', 'Provincia de Gerona'), 'en': ('Girona', 'Province of Girona'), 'ru': ('Жиро́на (Херо́на)', 'Жирона (провинция)')},
    'Granada'   : {'es': ('Granada', 'Provincia de Granada'), 'en': ('Granada', 'Province of Granada'), 'ru': ('Грана́да', 'Гранада (провинция)')},
    'Guadalajara'   : {'es': ('Guadalajara', 'Provincia de Guadalajara'), 'en': ('Guadalajara', 'Province of Guadalajara'), 'ru': ('Гвадалаха́ра', 'Гвадалахара (провинция)')},
    'Huelva'   : {'es': ('Huelva', 'Provincia de Huelva'), 'en': ('Huelva', 'Province of Huelva'), 'ru': ('Уэльва', 'Уэльва (провинция)')},
    'Huesca'   : {'es': ('Huesca', 'Provincia de Huesca'), 'en': ('Huesca', 'Province of Huesca'), 'ru': ('Уэ́ска', 'Уэска (провинция)')},
    'Jaén'   : {'es': ('Jaén', 'Provincia de Jaén (España)'), 'en': ('Jaén', 'Province of Jaén (Spain)'), 'ru': ('Хаэ́н', 'Хаэн (провинция)')},
    'León'   : {'es': ('León', 'Provincia de León'), 'en': ('León', 'Province of León'), 'ru': ('Лео́н', 'Леон (провинция)')},
    'Lleida'   : {'es': ('Lérida', 'Provincia de Lérida'), 'en': ('Lleida', 'Province of Lleida'), 'ru': ('Лье́йда (Ле́рида)', 'Льейда (провинция)')},
    'Lugo'   : {'es': ('Lugo', 'Provincia de Lugo'), 'en': ('Lugo', 'Province of Lugo'), 'ru': ('Лу́го', 'Луго (провинция)')},
    'Madrid'   : {'es': ('Madrid', 'Comunidad de Madrid'), 'en': ('Madrid', 'Community of Madrid'), 'ru': ('Мадри́д', 'Мадрид (автономное сообщество)')},
    'Melilla'   : {'es': ('Melilla (ciudad autónoma)', 'Melilla'), 'en': ('Melilla (auton. city)', 'Melilla'), 'ru': ('Мели́лья (автон. город)', 'Мелилья')},
    'Murcia'   : {'es': ('Murcia', 'Región de Murcia'), 'en': ('Murcia', 'Region of Murcia'), 'ru': ('Му́рсия', 'Мурсия (автономное сообщество)')},
    'Málaga'   : {'es': ('Málaga', 'Provincia de Málaga'), 'en': ('Málaga', 'Province of Málaga'), 'ru': ('Ма́лага', 'Малага (провинция)')},
    'Navarra'   : {'es': ('Navarra', 'Navarra'), 'en': ('Navarre', 'Navarre'), 'ru': ('Нава́рра', 'Наварра (автономное сообщество)')},
    'Ourense'   : {'es': ('Orense', 'Provincia de Orense'), 'en': ('Ourense', 'Province of Ourense'), 'ru': ('Оре́нсе', 'Оренсе (провинция)')},
    'Palencia'   : {'es': ('Palencia', 'Provincia de Palencia'), 'en': ('Palencia', 'Province of Palencia'), 'ru': ('Пале́нсия', 'Паленсия (провинция)')},
    'Palmas, Las'   : {'es': ('Las Palmas', 'Provincia de Las Palmas'), 'en': ('Las Palmas', 'Province of Las Palmas'), 'ru': ('Лас-Па́льмас', 'Лас-Пальмас (провинция)')},
    'Pontevedra'   : {'es': ('Pontevedra', 'Provincia de Pontevedra'), 'en': ('Pontevedra', 'Province of Pontevedra'), 'ru': ('Понтеве́дра', 'Понтеведра (провинция)')},
    'Rioja, La'   : {'es': ('La Rioja', 'La Rioja (España)'), 'en': ('La Rioja', 'La Rioja'), 'ru': ('Рио́ха (Ла-Рио́ха)', 'Риоха')},
    'Salamanca'   : {'es': ('Salamanca', 'Provincia de Salamanca'), 'en': ('Salamanca', 'Province of Salamanca'), 'ru': ('Салама́нка', 'Саламанка (провинция)')},
    'Santa Cruz de Tenerife'   : {'es': ('Santa Cruz de Tenerife', 'Provincia de Santa Cruz de Tenerife'), 'en': ('Santa Cruz de Tenerife', 'Province of Santa Cruz de Tenerife'), 'ru': ('Са́нта-Крус-де-Тенери́фе', 'Санта-Крус-де-Тенерифе (провинция)')},
    'Segovia'   : {'es': ('Segovia', 'Provincia de Segovia'), 'en': ('Segovia', 'Province of Segovia'), 'ru': ('Сего́вия', 'Сеговия (провинция)')},
    'Sevilla'   : {'es': ('Sevilla', 'Provincia de Sevilla'), 'en': ('Seville', 'Province of Seville'), 'ru': ('Севи́лья', 'Севилья (провинция)')},
    'Soria'   : {'es': ('Soria', 'Provincia de Soria'), 'en': ('Soria', 'Province of Soria'), 'ru': ('Со́рия', 'Сория (провинция)')},
    'Tarragona'   : {'es': ('Tarragona', 'Provincia de Tarragona'), 'en': ('Tarragona', 'Province of Tarragona'), 'ru': ('Тарраго́на', 'Таррагона (провинция)')},
    'Teruel'   : {'es': ('Teruel', 'Provincia de Teruel'), 'en': ('Teruel', 'Province of Teruel'), 'ru': ('Теруэ́ль', 'Теруэль (провинция)')},
    'Toledo'   : {'es': ('Toledo', 'Provincia de Toledo'), 'en': ('Toledo', 'Province of Toledo'), 'ru': ('Толе́до', 'Толедо (провинция)')},
    'Valencia/València'   : {'es': ('Valencia (València)', 'Provincia de Valencia'), 'en': ('Valencia (València)', 'Province of Valencia'), 'ru': ('Вале́нсия', 'Валенсия (провинция)')},
    'Valladolid'   : {'es': ('Valladolid', 'Provincia de Valladolid'), 'en': ('Valladolid', 'Province of Valladolid'), 'ru': ('Вальядоли́д', 'Вальядолид (провинция)')},
    'Zamora'   : {'es': ('Zamora', 'Provincia de Zamora'), 'en': ('Zamora', 'Province of Zamora'), 'ru': ('Самора', 'Самора (провинция)')},
    'Zaragoza'   : {'es': ('Zaragoza', 'Provincia de Zaragoza'), 'en': ('Zaragoza', 'Province of Zaragoza'), 'ru': ('Сараго́са', 'Сарагоса (провинция)')},
    'Ávila'   : {'es': ('Ávila', 'Provincia de Ávila'), 'en': ('Ávila', 'Province of Ávila'), 'ru': ('А́вила', 'Авила (провинция)')}
}

In [18]:
# create code for placing info in Wikipedia
def create_table_v1(df, file_header, lang='ru', is_extended=False):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=2, *, add_par=''):  # change_value
        return f'style="background:#fffae0;{add_par}"| —' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2, *, add_par=''):  # change_value
        return ' —' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''
    
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name == 'Spain':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2024"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["m_2024"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["f_2024"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["f-m_2024"])}\'\'\' ' + \
                  f'||style="border-left-width:2px;"| \'\'\'{if_value(ser["2014"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2014→2019"])} ' + \
                  f'|| \'\'\'{if_value(ser["2019"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2019→2020"])} ' + \
                  f'|| \'\'\'{if_value(ser["2020"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2020→2021"])} ' + \
                  f'|| \'\'\'{if_value(ser["2021"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2021→2022"])} ' + \
                  f'|| \'\'\'{if_value(ser["2022"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2022→2023"])} ' + \
                  f'|| \'\'\'{if_value(ser["2023"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2023→2024"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2024"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2014→2024"], add_par="border-left-width:2px;")}'
        else:
            name_link = dd_replacement[ser.name][lang][1]
            name_visible = dd_replacement[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2024"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["m_2024"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["f_2024"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["f-m_2024"])} ' + \
                  f'||style="border-left-width:2px;"| {if_value(ser["2014"])} ' + \
                  f'||{chval(ser["2014→2019"])} ' + \
                  f'|| {if_value(ser["2019"])} ' + \
                  f'||{chval(ser["2019→2020"])} ' + \
                  f'|| {if_value(ser["2020"])} ' + \
                  f'||{chval(ser["2020→2021"])} ' + \
                  f'|| {if_value(ser["2021"])} ' + \
                  f'||{chval(ser["2021→2022"])} ' + \
                  f'|| {if_value(ser["2022"])} ' + \
                  f'||{chval(ser["2022→2023"])} ' + \
                  f'|| {if_value(ser["2023"])} ' + \
                  f'||{chval(ser["2023→2024"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2024"])}\'\'\' ' + \
                  f'||{chval(ser["2014→2024"], add_par="border-left-width:2px;")}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"|—', ';color:silver;"|—')

    return st


table_code = create_table_v1(df, file_header='Spanish_header_ru -2024 -v1.txt', lang='ru')

# write the code to file
with open('output/Table code for Spanish provinces -ru -v1.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [19]:
table_code = create_table_v1(df, file_header='Spanish_header_en -2024 -v1.txt', lang='en')

# write the code to file
with open('output/Table code for Spanish provinces -en -v1.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br />
<br />

In [21]:
# create code for placing info in Wikipedia
def create_table_v2(df, file_header, lang='ru', is_extended=False):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=2, *, add_par=''):  # change_value
        return f'style="{add_par}"| —' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2, *, add_par=''):  # change_value
        return ' —' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''
    
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name == 'Spain':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2014"])} ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["m_2014"])} ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["f_2014"])} ' + \
                  f'||style="background:#fffae0;"| \'\'\'{if_value(ser["f-m_2014"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2014→2019"], add_par="border-left-width:2px;padding-right:1.5ex;")} ' + \
                  f'||style="border-left-width:2px;background:#e0ffd8;"| \'\'\'{if_value(ser["2019"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["m_2019"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["f_2019"])}\'\'\' ' + \
                  f'||style="background:#fffae0;"| \'\'\'{if_value(ser["f-m_2019"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2019→2024"], add_par="border-left-width:2px;padding-right:1.5ex;")} ' + \
                  f'||style="border-left-width:2px;background:#e0ffd8;"| \'\'\'{if_value(ser["2024"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["m_2024"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["f_2024"])}\'\'\' ' + \
                  f'||style="background:#fffae0;"| \'\'\'{if_value(ser["f-m_2024"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2014→2024"], add_par="border-left-width:2px;padding-right:1.5ex;")}'
        else:
            name_link = dd_replacement[ser.name][lang][1]
            name_visible = dd_replacement[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser["2014"])} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["m_2014"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["f_2014"])} ' + \
                  f'||style="background:#fffae0;"| {if_value(ser["f-m_2014"])} ' + \
                  f'||{chval(ser["2014→2019"], add_par="border-left-width:2px;padding-right:1.5ex;")} ' + \
                  f'||style="border-left-width:2px;background:#e0ffd8;"| {if_value(ser["2019"])} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["m_2019"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["f_2019"])} ' + \
                  f'||style="background:#fffae0;"| {if_value(ser["f-m_2019"])} ' + \
                  f'||{chval(ser["2019→2024"], add_par="border-left-width:2px;padding-right:1.5ex;")} ' + \
                  f'||style="border-left-width:2px;background:#e0ffd8;"| {if_value(ser["2024"])} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["m_2024"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["f_2024"])} ' + \
                  f'||style="background:#fffae0;"| {if_value(ser["f-m_2024"])} ' + \
                  f'||{chval(ser["2014→2024"], add_par="border-left-width:2px;padding-right:1.5ex;")}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')
        
    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"|—', ';color:silver;"|—')

    return st


table_code = create_table_v2(df, file_header='Spanish_header_ru -2024 -v2.txt', lang='ru')

# write the code to file
with open('output/Table code for Spanish provinces -ru -v2.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [22]:
table_code = create_table_v2(df, file_header='Spanish_header_en -2024 -v2.txt', lang='en')

# write the code to file
with open('output/Table code for Spanish provinces -en -v2.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)