Data sources: [Statistics Canada](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310083701) <i>("download entire table")</i><br>
[List of Canadian provinces and territories by life expectancy](https://en.wikipedia.org/wiki/List_of_Canadian_provinces_and_territories_by_life_expectancy) / [Продолжительность жизни в провинциях и территориях Канады](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_провинциях_и_территориях_Канады)

In [2]:
import pandas as pd
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

# from collections import namedtuple

In [3]:
# load data
df = pd.read_csv('data/Canada-1year-2024.zip', compression='zip',
                 usecols = ['REF_DATE', 'GEO', 'Age group', 'Sex', 'Element', 'VALUE'])

df= df.loc[(df['Age group'] == '0 years') & (df['Element'] == 'Life expectancy (in years) at age x (ex)') & (df['REF_DATE'] >= 2010)]

df.head(2)

,REF_DATE,GEO,Age group,Sex,Element,VALUE
899107,2010,Canada,0 years,Both sexes,Life expectancy (in years) at age x (ex),81.43
899116,2010,Canada,0 years,Males,Life expectancy (in years) at age x (ex),79.21

In [4]:
df = df.drop(columns=['Age group', 'Element']) \
       .rename(columns={'REF_DATE': 'year',
                        'GEO': 'region',
                        'Sex': 'sex',
                        'VALUE': 'value'})
df

         year                     region         sex  value
899107   2010                     Canada  Both sexes  81.43
899116   2010                     Canada       Males  79.21
899125   2010                     Canada     Females  83.54
902104   2010  Newfoundland and Labrador  Both sexes  79.57
902113   2010  Newfoundland and Labrador       Males  77.10
...       ...                        ...         ...    ...
1342672  2024                    Alberta       Males  79.32
1342681  2024                    Alberta     Females  83.87
1345660  2024           British Columbia  Both sexes  82.58
1345669  2024           British Columbia       Males  80.16
1345678  2024           British Columbia     Females  85.07

[450 rows x 4 columns]

<br>
<br>

In [6]:
df_total = df.loc[df['sex'] == 'Both sexes'] \
             .pivot(index='region', columns='year', values='value')

df_total.index.name = df_total.columns.name = ''

df_total

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
,,,,,,,,,,,,,,,
Alberta,81.18,81.26,81.33,81.22,81.34,81.45,81.50,81.38,81.44,81.96,80.84,80.24,80.19,80.71,81.53
British Columbia,82.22,82.33,82.55,82.56,82.69,82.62,82.36,82.05,82.20,82.74,82.09,81.34,81.45,81.96,82.58
Canada,81.43,81.58,81.76,81.84,81.87,81.92,82.02,81.88,81.87,82.22,81.58,81.50,81.13,81.68,82.16
Manitoba,79.92,79.84,80.09,80.28,79.82,80.13,80.00,79.96,80.04,80.19,79.29,79.29,78.46,79.08,79.29
New Brunswick,80.78,81.12,80.93,81.08,81.05,80.65,80.74,80.81,80.57,80.71,81.04,80.89,79.58,80.41,80.44
Newfoundland and Labrador,79.57,79.85,79.51,79.34,79.30,79.22,79.68,79.89,79.98,80.07,79.73,79.46,78.87,79.03,79.61
Nova Scotia,80.29,80.21,80.56,80.39,80.55,80.22,80.62,80.41,80.44,80.43,80.56,80.47,79.71,80.49,80.70
Ontario,81.79,82.03,82.23,82.32,82.33,82.46,82.46,82.33,82.29,82.55,81.99,81.92,81.69,82.29,82.85
Quebec,81.48,81.62,81.73,81.99,82.06,82.12,82.57,82.44,82.42,82.84,82.18,82.84,82.03,82.52,82.65
Saskatchewan,79.63,79.72,80.26,80.03,80.07,80.14,80.35,80.30,80.14,80.50,79.36,78.53,78.57,78.98,79.66

In [7]:
df_male = df.loc[df['sex'] == 'Males'] \
             .pivot(index='region', columns='year', values='value')

df_male.index.name = df_male.columns.name = ''

df_male

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
,,,,,,,,,,,,,,,
Alberta,78.94,79.11,79.13,79.20,79.31,79.23,79.30,79.11,79.09,79.86,78.47,77.62,77.90,78.38,79.32
British Columbia,80.20,80.23,80.53,80.53,80.53,80.55,80.17,79.61,79.75,80.55,79.37,78.62,78.75,79.30,80.16
Canada,79.21,79.39,79.61,79.74,79.76,79.86,79.94,79.72,79.75,80.10,79.33,79.11,78.89,79.48,80.03
Manitoba,77.70,77.53,77.95,77.89,77.60,78.15,77.87,77.85,77.97,78.03,77.04,76.79,75.91,76.84,76.93
New Brunswick,78.41,78.68,78.56,78.93,79.08,78.42,78.65,78.69,78.56,78.45,78.97,78.77,77.53,78.40,78.44
Newfoundland and Labrador,77.10,77.65,76.92,77.47,77.04,77.23,77.52,77.88,77.93,78.05,77.81,77.26,76.94,76.98,77.56
Nova Scotia,77.83,77.98,78.50,78.11,78.29,78.19,78.26,78.25,78.29,78.48,78.49,78.14,77.53,78.32,78.59
Ontario,79.60,79.88,80.11,80.18,80.21,80.47,80.39,80.20,80.19,80.38,79.71,79.54,79.44,80.09,80.68
Quebec,79.25,79.41,79.60,80.01,80.10,80.15,80.76,80.55,80.61,80.92,80.38,80.83,80.20,80.73,80.90
Saskatchewan,77.21,77.33,77.92,77.79,77.74,77.75,78.15,77.98,77.94,78.24,76.74,76.06,76.20,76.70,77.43

In [8]:
df_female = df.loc[df['sex'] == 'Females'] \
             .pivot(index='region', columns='year', values='value')

df_female.index.name = df_female.columns.name = ''

df_female

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
,,,,,,,,,,,,,,,
Alberta,83.47,83.48,83.50,83.26,83.43,83.73,83.78,83.77,83.93,84.11,83.35,83.10,82.60,83.15,83.87
British Columbia,84.22,84.41,84.56,84.60,84.86,84.67,84.56,84.58,84.75,84.96,84.90,84.18,84.28,84.73,85.07
Canada,83.54,83.68,83.82,83.85,83.91,83.89,84.04,84.00,83.96,84.32,83.84,83.91,83.41,83.88,84.29
Manitoba,82.15,82.08,82.22,82.66,82.11,82.14,82.28,82.11,82.29,82.54,81.62,82.02,81.25,81.47,81.85
New Brunswick,83.07,83.45,83.15,83.12,82.92,82.91,82.70,82.89,82.38,83.00,83.10,82.86,81.68,82.46,82.49
Newfoundland and Labrador,82.02,81.84,82.01,81.09,81.61,81.24,81.86,81.85,81.95,82.13,81.75,81.58,80.75,81.08,81.59
Nova Scotia,82.51,82.30,82.47,82.55,82.79,82.19,82.88,82.40,82.48,82.29,82.59,82.82,81.95,82.75,82.85
Ontario,83.85,84.07,84.24,84.34,84.35,84.33,84.44,84.39,84.32,84.67,84.26,84.29,83.94,84.49,84.99
Quebec,83.54,83.67,83.71,83.86,83.93,84.01,84.29,84.24,84.12,84.71,83.93,84.79,83.82,84.28,84.39
Saskatchewan,82.17,82.21,82.73,82.40,82.50,82.66,82.86,82.83,82.53,82.95,82.19,81.17,81.13,81.38,82.05

<br>
<br>

In [10]:
df_provinces = pd.concat([
        df_total[2019], df_male[2019], df_female[2019], (df_female[2019]-df_male[2019]).round(2),
        (df_total[2023]-df_total[2019]).round(2),
        df_total[2023], df_male[2023], df_female[2023], (df_female[2023]-df_male[2023]).round(2),
        (df_total[2024]-df_total[2023]).round(2),
        df_total[2024], df_male[2024], df_female[2024], (df_female[2024]-df_male[2024]).round(2),
        (df_total[2024]-df_total[2019]).round(2)],
    axis='columns',
    keys=['2019_t', '2019_m', '2019_f', '2019_fΔm', '2019→2023',
          '2023_t', '2023_m', '2023_f', '2023_fΔm', '2023→2024',
          '2024_t', '2024_m', '2024_f', '2024_fΔm', '2019→2024']
)

del df, df_total, df_male, df_female

df_provinces.sort_values(['2024_t', '2024_m', '2024_f'], ascending=False, inplace=True)
df_provinces = pd.concat([df_provinces.loc[['Canada']], df_provinces.drop(index='Canada')])

df_provinces

,2019_t,2019_m,2019_f,2019_fΔm,2019→2023,2023_t,2023_m,2023_f,2023_fΔm,2023→2024,2024_t,2024_m,2024_f,2024_fΔm,2019→2024
,,,,,,,,,,,,,,,
Canada,82.22,80.10,84.32,4.22,-0.54,81.68,79.48,83.88,4.40,0.48,82.16,80.03,84.29,4.26,-0.06
Ontario,82.55,80.38,84.67,4.29,-0.26,82.29,80.09,84.49,4.40,0.56,82.85,80.68,84.99,4.31,0.30
Quebec,82.84,80.92,84.71,3.79,-0.32,82.52,80.73,84.28,3.55,0.13,82.65,80.90,84.39,3.49,-0.19
British Columbia,82.74,80.55,84.96,4.41,-0.78,81.96,79.30,84.73,5.43,0.62,82.58,80.16,85.07,4.91,-0.16
Alberta,81.96,79.86,84.11,4.25,-1.25,80.71,78.38,83.15,4.77,0.82,81.53,79.32,83.87,4.55,-0.43
Nova Scotia,80.43,78.48,82.29,3.81,0.06,80.49,78.32,82.75,4.43,0.21,80.70,78.59,82.85,4.26,0.27
New Brunswick,80.71,78.45,83.00,4.55,-0.30,80.41,78.40,82.46,4.06,0.03,80.44,78.44,82.49,4.05,-0.27
Saskatchewan,80.50,78.24,82.95,4.71,-1.52,78.98,76.70,81.38,4.68,0.68,79.66,77.43,82.05,4.62,-0.84
Newfoundland and Labrador,80.07,78.05,82.13,4.08,-1.04,79.03,76.98,81.08,4.10,0.58,79.61,77.56,81.59,4.03,-0.46
Manitoba,80.19,78.03,82.54,4.51,-1.11,79.08,76.84,81.47,4.63,0.21,79.29,76.93,81.85,4.92,-0.90

<br>
<br>

In [12]:
# just for interest, explore results: determine regions with max and min values, and also look at specific regions
mal.min_and_max_values(df_provinces[['2019_t', '2019→2023', '2023_t', '2023→2024', '2024_t', '2019→2024']], max_lng=25, row_center='Canada')

Number of records: 10

In [13]:
mal.min_and_max_values(df_provinces[['2019_m', '2023_m', '2024_m', '2019_f', '2023_f', '2024_f']], max_lng=25, row_center='Canada')

Number of records: 10

<br>
<br>

In [15]:
# for region in sorted(df.index.to_list()):
#     print(f"    '{region}': {{'en': ('', ''), 'ru': ('', '')}},")

In [16]:
dd_replacement = {
    'Canada': {'en': ('Canada on average', ''), 'ru': ('Канада в среднем', '')},
    'Alberta': {'en': ('Alberta', 'Alberta'), 'ru': ('Альбе́рта', 'Альберта')},
    'British Columbia': {'en': ('British Columbia', 'British Columbia'), 'ru': ('Британская Колу́мбия', 'Британская Колумбия')},
    'Manitoba': {'en': ('Manitoba', 'Manitoba'), 'ru': ('Манито́ба', 'Манитоба')},
    'New Brunswick': {'en': ('New Brunswick', 'New Brunswick'), 'ru': ('Нью-Бра́нсуик', 'Нью-Брансуик')},
    'Newfoundland and Labrador': {'en': ('Newfoundland and Labrador', 'Newfoundland and Labrador'), 'ru': ('Ньюфа́ундленд и Лабрадо́р', 'Ньюфаундленд и Лабрадор')},
    'Nova Scotia': {'en': ('Nova Scotia', 'Nova Scotia'), 'ru': ('Новая Шотла́ндия', 'Новая Шотландия')},
    'Ontario': {'en': ('Ontario', 'Ontario'), 'ru': ('Онта́рио', 'Онтарио')},
    'Quebec': {'en': ('Quebec', 'Quebec'), 'ru': ('Квебе́к', 'Квебек')},
    'Saskatchewan': {'en': ('Saskatchewan', 'Saskatchewan'), 'ru': ('Саскaчевáн', 'Саскачеван')}
}

In [17]:
# create code for placing info in Wikipedia
def create_table_regions(df, file_header, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=2, *, add_par=''):  # change_value
        return f'style="padding-right:1.5ex;{add_par}"| —' if math.isnan(x) else \
               f'style="padding-right:1.5ex;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'style="padding-right:1.5ex;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2, *, add_par=''):  # change_value
        return ' \'\'\'—\'\'\'' if math.isnan(x) else \
               f'style="padding-right:1.5ex;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="padding-right:1.5ex;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]    
        if ser.name == 'Canada':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2019_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2019_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2019_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2019_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2019→2023"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2023_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2023_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2023_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2023_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2023→2024"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2024_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2024_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2024_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2024_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["2019→2024"], add_par="border-left-width:2px;")}'
        else:
            name_link = dd_replacement[ser.name][lang][1]
            name_visible = dd_replacement[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2019_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2019_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2019_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2019_fΔm"])} ' + \
                  f'||{chval(ser["2019→2023"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2023_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2023_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2023_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2023_fΔm"])} ' + \
                  f'||{chval(ser["2023→2024"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2024_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2024_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2024_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2024_fΔm"])} ' + \
                  f'||{chval(ser["2019→2024"], add_par="border-left-width:2px;")}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —')

    return st


table_code = create_table_regions(df_provinces, file_header='Canada_header_1year_en -2024.txt', lang='en')

# write the code to file
with open('output/Table code for Canada -1_year -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [18]:
table_code = create_table_regions(df_provinces, file_header='Canada_header_1year_ru -2024.txt', lang='ru')

# write the code to file
with open('output/Table code for Canada -1_year -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br>
<br>