[my svg](https://commons.wikimedia.org/wiki/File:Comparison_gender_life_expectancy_WHO.svg)<br>
[original svg](https://commons.wikimedia.org/wiki/File:Comparison_gender_life_expectancy_CIA_factbook.svg)<br>
[List of countries by population](https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations))<br>
[List of countries by life expectancy](https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy#World_Health_Organization_(2019))<br>
[selection of colors](http://mal-bioit.ru/programs/small/survey-web-colors.html)

[UN demographic indicators](https://population.un.org/wpp/downloads?folder=Standard%20Projections&group=Most%20used)<br>
WHO > [The Global Health Observatory: Explore a world of health data](https://www.who.int/data/gho/data/themes/topics/indicator-groups/indicator-group-details/GHO/life-expectancy-and-healthy-life-expectancy)<br />
WHO > [Life expectancy at birth](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years))<br />
WHO > [Healthy life expectancy (HALE) at birth](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/gho-ghe-hale-healthy-life-expectancy-at-birth)

Lists of countries by life expectancy: [world](https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy) <i>([template](https://en.wikipedia.org/wiki/Template:List_of_countries_by_life_expectancy/World_Health_Organization))</i>, [Europe](https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy), [Asia](https://en.wikipedia.org/wiki/List_of_Asian_countries_by_life_expectancy), [North America](https://en.wikipedia.org/wiki/List_of_North_American_countries_by_life_expectancy), [South America](https://en.wikipedia.org/wiki/List_of_South_American_countries_by_life_expectancy), [Americas (combined)](https://en.wikipedia.org/wiki/List_of_countries_in_the_Americas_by_life_expectancy), [Africa](https://en.wikipedia.org/wiki/List_of_African_countries_by_life_expectancy), [regions](https://en.wikipedia.org/wiki/List_of_world_regions_by_life_expectancy), [EU](https://en.wikipedia.org/wiki/Demographics_of_the_European_Union#Life_expectancy)<br />
[my private wiki-page for exploration](https://en.wikipedia.org/wiki/User:Lady3mlnm/HALE)<br>
Списки стран по ожидаемой продолжительности жизни: [мир в целом](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни), [Европа](https://ru.wikipedia.org/wiki/Список_стран_Европы_по_ожидаемой_продолжительности_жизни), [Азия](https://ru.wikipedia.org/wiki/Список_стран_Азии_по_ожидаемой_продолжительности_жизни), [Северная Америка](https://ru.wikipedia.org/wiki/Список_стран_Южной_Америки_по_ожидаемой_продолжительности_жизни), [Северная Америка](https://ru.wikipedia.org/wiki/Список_стран_Южной_Америки_по_ожидаемой_продолжительности_жизни),  [Африка](https://ru.wikipedia.org/wiki/Список_стран_Африки_по_ожидаемой_продолжительности_жизни), [регионы](https://ru.wikipedia.org/wiki/Список_регионов_мира_по_ожидаемой_продолжительности_жизни), [ЕС](https://ru.wikipedia.org/wiki/Население_стран_Европейского_союза#Продолжительность_жизни), [СНГ](https://ru.wikipedia.org/wiki/Содружество_Независимых_Государств#Социальное_развитие_стран_СНГ)

In [2]:
import pandas as pd
from data_service.dictionary_eng_rus_for_svg import dd_to_rus, dd_decryption  # dictionary for translation of names and decryption of abbreviation

In [3]:
pd.options.display.min_rows = 6
pd.options.display.max_rows = 100
pd.options.display.float_format = '{:.2f}'.format

In [4]:
YEAR_SELECTED = 2019

# If database process the first time or was updated, set the constant as True - intermediate calculations will be saved
# to dist to speed up further processing.
# If the constant is set as False, data will be taken from file with intermediate calculations but not from the original database.
IS_FIRST_ANALYSIS = True

Load data for number of people in countries:

In [6]:
# if data is loaded from the original database
if IS_FIRST_ANALYSIS:
    
    # load data from original XLSX-file
    pop = pd.read_excel('data/UN_demographic_indicators.xlsx', sheet_name='Estimates', skiprows=16, na_values='...',
                       usecols=['Region, subregion, country or area *', 'Location code', 'Year', 'Total Population, as of 1 January (thousands)', 'Total Population, as of 1 July (thousands)']) \
           .rename(columns={'Region, subregion, country or area *': 'region',
                            'Location code': 'code',
                            'Year': 'year',
                            'Total Population, as of 1 January (thousands)': 'population_Jan',
                            'Total Population, as of 1 July (thousands)': 'population_Jul'})
    
    pop = pop.loc[pop.year == YEAR_SELECTED] \
             .drop(columns='year') \
             .set_index('region')
    
    # population was in thousands - remake it to number
    pop['population_Jan'] = (pop['population_Jan']*1000).astype('int64')
    pop['population_Jul'] = (pop['population_Jul']*1000).astype('int64')
    pop.index.name = ''

    print(f"Number of values with duplicates: {len(pop)}")
    
    # remove values with duplicated index (these are 'Latin America and the Caribbean' and 'Australia/New Zealand'
    pop = pop[~pop.index.duplicated(keep='last')]

    # save intermediate data to file
    pop.to_csv('data/UN_demographic_indicators-intermediate_calculations.csv', index=True)
    print("Intermediate data is written to file")

# if data is loaded from file with intermediate calculations
else:
    pop = pd.read_csv('data/UN_demographic_indicators-intermediate_calculations.csv')
    print("Data is loaded from file with intermediate data")


print(len(pop))         
pop.loc[['World', 'Russian Federation', 'United States of America', 'France', 'Spain', 'Japan',
         'Switzerland', 'Republic of Korea', 'China', 'India']].sort_values(by='population_Jan', ascending=False)

Number of values with duplicates: 297
Intermediate data is written to file
295

                          code  population_Jan  population_Jul

World                      900      7771172776      7811293698
China                      156      1421604871      1423520357
India                      356      1382089548      1389030312
United States of America   840       336437705       337790067
Russian Federation         643       146511509       146533067
Japan                      392       126823995       126699424
France                     250        65642126        65729459
Republic of Korea          410        51709893        51767846
Spain                      724        47233166        47435119
Switzerland                756         8546621         8577524

In [7]:
country_code = pd.read_csv('data_service/country-code-region_connection.csv', sep='\t', index_col=0)
country_code.index.name = ''
country_code

                          region choice         subregion subregion abbr  code

World                          -      -                 -              -   900
Africa                         -      -                 -              -   903
Asia                           -      -                 -              -   935
...                          ...    ...               ...            ...   ...
Greenland                     na     na  Northern America            nam   304
Saint Pierre and Miquelon     na     na  Northern America            nam   666
United States of America      na     na  Northern America            nam   840

[245 rows x 5 columns]

<br>
<br>

exploration of dataFrames:

In [9]:
ls_pop = pop.index.to_list()
print(len(ls_pop))

295

In [10]:
ls_country_code = country_code.index.to_list()
print(len(ls_country_code))

245

In [11]:
[country for country in ls_pop if country not in ls_country_code]

['Sub-Saharan Africa',
 'Northern Africa and Western Asia',
 'Central and Southern Asia',
 'Eastern and South-Eastern Asia',
 'Oceania (excluding Australia and New Zealand)',
 'Europe and Northern America',
 'Europe, Northern America, Australia, and New Zealand',
 'More developed regions',
 'Less developed regions',
 'Least developed countries',
 'Less developed regions, excluding least developed countries',
 'Less developed regions, excluding China',
 'Land-locked Developing Countries (LLDC)',
 'LLDC: Africa',
 'LLDC: Asia',
 'LLDC: Europe',
 'LLDC: Latin America',
 'Small Island Developing States (SIDS)',
 'SIDS Caribbean',
 'SIDS Pacific',
 'SIDS Atlantic, Indian Ocean and South China Sea (AIS)',
 'High-and-upper-middle-income countries',
 'Low-and-Lower-middle-income countries',
 'High-income countries',
 'Low-and-middle-income countries',
 'Middle-income countries',
 'Upper-middle-income countries',
 'Lower-middle-income countries',
 'Low-income countries',
 'No income group available',
 'Eastern Africa',
 'Middle Africa',
 'Northern Africa',
 'Southern Africa',
 'Western Africa',
 'Central Asia',
 'Eastern Asia',
 'Southern Asia',
 'South-Eastern Asia',
 'Western Asia',
 'Eastern Europe',
 'Northern Europe',
 'Southern Europe',
 'Kosovo (under UNSC res. 1244)',
 'Western Europe',
 'Caribbean',
 'Central America',
 'South America',
 'Australia/New Zealand',
 'Melanesia',
 'Micronesia',
 'Polynesia']

In [12]:
[country for country in ls_country_code if country not in ls_pop]

['Channel Islands']

<br>
<br>

In [14]:
pop = pop.merge(country_code, left_index=True, right_index=True)
pop

,code_x,population_Jan,population_Jul,region,choice,subregion,subregion abbr,code_y
,,,,,,,,
World,900,7771172776,7811293698,-,-,-,-,900
Africa,903,1331734591,1348005492,-,-,-,-,903
Burundi,108,12069367,12255336,af,af,Eastern Africa,afe,108
...,...,...,...,...,...,...,...,...
Tonga,776,105643,105669,oc,oc,Oceania,oc,776
Tuvalu,798,10670,10581,oc,oc,Oceania,oc,798
Wallis and Futuna Islands,876,11740,11686,oc,oc,Oceania,oc,876

In [15]:
assert len(pop.loc[pop['code_x'] != pop['code_y']]) == 0

In [16]:
ls_drop = ['World', 'Africa', 'Asia', 'Europe', 'Latin America and the Caribbean', 'Northern America', 'Oceania',
           'Mayotte', 'Réunion', 'Saint Helena', 'Western Sahara', 'State of Palestine', 'Anguilla', 'Aruba',
           'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands', 'Cayman Islands', 'Curaçao', 'Dominica',
           'Guadeloupe', 'Martinique', 'Montserrat', 'Saint Barthélemy', 'Saint Kitts and Nevis',
           'Saint Martin (French part)', 'Sint Maarten (Dutch part)', 'Turks and Caicos Islands',
           'United States Virgin Islands', 'Falkland Islands (Malvinas)', 'French Guiana', 'New Caledonia', 'Guam',
           'Marshall Islands', 'Nauru', 'Northern Mariana Islands', 'Palau', 'American Samoa', 'Cook Islands',
           'French Polynesia', 'Niue', 'Tokelau', 'Tuvalu', 'Wallis and Futuna Islands',
           'Faroe Islands', 'Andorra', 'Gibraltar', 'Holy See', 'San Marino', 'Liechtenstein',
           'Monaco', 'Bermuda', 'Greenland', 'Saint Pierre and Miquelon',
           'Isle of Man', 'Jersey', 'Guernsey']

pop = pop.drop(index=ls_drop,
               columns=['code_x', 'code_y', 'population_Jan', 'region','subregion']) \
         .rename(columns={'population_Jul':'pop',
                          'choice': 'choice_1',
                          'subregion abbr': 'choice_2'},
                 index={'Bolivia (Plurinational State of)': 'Bolivia',
                        'Brunei Darussalam': 'Brunei',
                        'Cabo Verde': 'Cape Verde',
                        'Central African Republic': 'CAR',
                        'Congo': 'Congo Republic',
                        "Dem. People's Republic of Korea": 'North Korea',
                        'Democratic Republic of the Congo': 'Congo DR',
                        'Iran (Islamic Republic of)': 'Iran',
                        "Lao People's Democratic Republic": 'Laos',
                        'Micronesia (Fed. States of)': 'Micronesia',
                        'Republic of Korea': 'South Korea',
                        'Republic of Moldova': 'Moldova',
                        'Russian Federation': 'Russia',
                        'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
                        'Syrian Arab Republic': 'Syria',
                        'Türkiye': 'Turkey',
                        'United Arab Emirates': 'UAE',
                        'United Kingdom': 'UK',
                        'United Republic of Tanzania': 'Tanzania',
                        'United States of America': 'USA',
                        'Venezuela (Bolivarian Republic of)': 'Venezuela',
                        'Viet Nam': 'Vietnam'})

pop

                 pop choice_1 choice_2

Burundi     12255336       af      afe
Comoros       786578       af      afe
Djibouti     1088709       af      afe
...              ...      ...      ...
Micronesia    110282       oc       oc
Samoa         209780       oc       oc
Tonga         105669       oc       oc

[187 rows x 3 columns]

In [17]:
# pop.index.to_list()

In [18]:
# Combine special provinces of China with China mainland
print('China before combining:', pop.loc['China', 'pop'])

pop.loc['China', 'pop'] += pop.loc['China, Hong Kong SAR', 'pop'] + pop.loc['China, Macao SAR', 'pop'] + pop.loc['China, Taiwan Province of China', 'pop']
pop = pop.drop(index=['China, Hong Kong SAR', 'China, Macao SAR', 'China, Taiwan Province of China'])

print('China after combining :', pop.loc['China', 'pop'])

China before combining: 1423520357
China after combining : 1455351282

In [19]:
print(f"number or records in dataFrame now: {len(pop)}")

number or records in dataFrame now: 184

<br>

In [21]:
dd_countries_ignore = ['occupied Palestinian territory, including east Jerusalem']
dd_countries_renaming = {
	'Bolivia (Plurinational State of)': 'Bolivia',
	'Brunei Darussalam': 'Brunei',
	'Cabo Verde': 'Cape Verde',
	"Democratic People's Republic of Korea": 'North Korea',
	'Democratic Republic of the Congo': 'Congo DR',
    'Congo': 'Congo Republic',
	'Iran (Islamic Republic of)': 'Iran',
	"Lao People's Democratic Republic": 'Laos',
	'Micronesia (Federated States of)': 'Micronesia',  # !check that the database does not contain region "Micronesia"
	'Netherlands (Kingdom of the)': 'Netherlands',
	'Republic of Korea': 'South Korea',
	'Republic of Moldova': 'Moldova',
	'Russian Federation': 'Russia',
	'Syrian Arab Republic': 'Syria',
    'Türkiye': 'Turkey',
	'United Kingdom of Great Britain and Northern Ireland': 'UK',
	'United Republic of Tanzania': 'Tanzania',
	'United States of America': 'USA',
	'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    "Cote d'Ivoire": "Côte d'Ivoire",
    'United Arab Emirates': 'UAE',
    'Central African Republic': 'CAR'
}

In [22]:
def load_data_from_csv(file_name, selected_indicator, selected_year=YEAR_SELECTED, prefix_for_cols=''):
    df = pd.read_csv(f"data/{file_name}",
                     usecols=['Indicator', 'Location', 'Period', 'Dim1', 'FactValueNumeric'])

    df.rename(columns={'Location': 'country',
                       'Period': 'year',
                       'Dim1': 'sex',
                       'FactValueNumeric': 'value'}, inplace=True)

    
    df = df[(df.Indicator == selected_indicator) & (df.year == selected_year)] \
              .drop(columns=['Indicator', 'year'])

    df = df[~df['country'].isin(dd_countries_ignore)]
    df['country'] = df['country'].replace(dd_countries_renaming)
    df = df.pivot(index='country', columns='sex', values='value')

    df = df[['Both sexes', 'Male', 'Female']]                       # just reorder
    df.rename(columns = {'Both sexes': f"{prefix_for_cols}o",
                         'Male': f"{prefix_for_cols}m",
                         'Female': f"{prefix_for_cols}f"}, inplace=True)
    df.index.name = ''
    df.columns.name = ''
    df[f"{prefix_for_cols}fΔm"] = (df[f"{prefix_for_cols}f"] - df[f"{prefix_for_cols}m"]).round(2)
    return df

df_le = load_data_from_csv(file_name="Life expectancy at birth -countries.csv",
                           selected_indicator="Life expectancy at birth (years)",
                           prefix_for_cols="LE_")
df_le

             LE_o  LE_m  LE_f  LE_fΔm

Afghanistan 61.22 60.04 62.55    2.51
Albania     77.94 76.17 79.87    3.70
Algeria     76.55 76.24 77.08    0.84
...           ...   ...   ...     ...
Yemen       66.90 63.95 70.01    6.06
Zambia      61.76 59.43 63.95    4.52
Zimbabwe    59.07 56.90 61.02    4.12

[184 rows x 4 columns]

In [23]:
df_hale = load_data_from_csv(file_name="Healthy life expectancy (HALE) at birth -countries.csv",
                             selected_indicator="Healthy life expectancy (HALE) at birth (years)",
                             prefix_for_cols="HALE_")
df_hale

             HALE_o  HALE_m  HALE_f  HALE_fΔm

Afghanistan   52.31   51.87   52.84      0.97
Albania       68.41   67.48   69.43      1.95
Algeria       66.14   67.04   65.34     -1.70
...             ...     ...     ...       ...
Yemen         57.36   56.40   58.35      1.95
Zambia        53.87   52.67   54.97      2.30
Zimbabwe      51.95   50.90   52.93      2.03

[184 rows x 4 columns]

In [24]:
# check just in case
assert set(pop.index.to_list()) == set(df_le.index.to_list()) == set(df_hale.index.to_list()), 'Indexes of dataFrames are not identical'

In [25]:
df = pd.concat([pop, df_le, df_hale], axis='columns').sort_values(by='pop', ascending=False)
df = df[['pop', 'LE_o', 'LE_m', 'LE_f', 'LE_fΔm', 'HALE_o', 'HALE_m', 'HALE_f', 'HALE_fΔm', 'choice_1', 'choice_2']] # just 
df.insert(loc=9,  value=100 * df['HALE_o'] / df['LE_o'], column='ratio_o')
df.insert(loc=10, value=100 * df['HALE_m'] / df['LE_m'], column='ratio_m')
df.insert(loc=11, value=100 * df['HALE_f'] / df['LE_f'], column='ratio_f')

del pop, df_le, df_hale

df

,pop,LE_o,LE_m,LE_f,LE_fΔm,HALE_o,HALE_m,HALE_f,HALE_fΔm,ratio_o,ratio_m,ratio_f,choice_1,choice_2
,,,,,,,,,,,,,,
China,1455351282,77.31,74.58,80.36,5.78,68.45,66.99,70.08,3.09,88.54,89.82,87.21,ase,ase
India,1389030312,70.73,69.18,72.41,3.23,60.88,60.70,61.08,0.38,86.07,87.74,84.35,ass,ass
USA,337790067,78.74,76.53,80.98,4.45,66.02,65.13,66.93,1.80,83.85,85.10,82.65,na,nam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tonga,105669,72.94,70.38,75.60,5.22,64.05,62.97,65.21,2.24,87.81,89.47,86.26,oc,oc
St. Vincent and the Grenadines,104167,73.11,70.76,75.82,5.06,63.49,62.21,64.98,2.77,86.84,87.92,85.70,na,car
Antigua and Barbuda,91364,75.66,74.05,77.07,3.02,65.78,65.16,66.31,1.15,86.94,87.99,86.04,na,car

<br />
<br />

In [27]:
# load instructins how data should be handled
handling = pd.read_csv('data_service/WHO_handling_for_svg.csv', index_col=0)

# transform to dictionary
colors_all, regions_all = handling.to_dict('dict').values()
del handling
colors_all

{'euw': '#6600cc',
 'eun': '#6495ed',
 'eus': '#cc00cc',
 'eue': '#008000',
 'asc': '#993300',
 'asw': '#004800',
 'ass': '#d2691e',
 'ase': '#ff0000',
 'asse': '#808000',
 'oc': '#0000ff',
 'na': '#0099cc',
 'sa': '#32cd32',
 'af': '#696969',
 '-': '#999999',
 'nam': '#0000ff',
 'car': '#ba55d3',
 'ca': '#d2691e',
 'afn': '#008000',
 'afw': '#4169e1',
 'afm': '#696969',
 'afe': '#dc143c',
 'afs': '#a0522d'}

In [28]:
regions_all

{'euw': 'Europe Western',
 'eun': 'Europe Northern',
 'eus': 'Europe Southern',
 'eue': 'Europe Eastern',
 'asc': 'Asia Central',
 'asw': 'Asia Western',
 'ass': 'Asia South',
 'ase': 'Asia Eastern',
 'asse': 'Asia South-Eastern',
 'oc': 'Oceania',
 'na': 'North America',
 'sa': 'South America',
 'af': 'Africa',
 '-': 'other',
 'nam': 'North America',
 'car': 'Caribbean',
 'ca': 'Central America',
 'afn': 'Africa Northern',
 'afw': 'Africa Western',
 'afm': 'Africa Middle',
 'afe': 'Africa Eastern',
 'afs': 'Africa Southern'}

In [29]:
# print(list(regions.keys()), sep=', ')

<br />
<br />

In [31]:
df.head(3)

,pop,LE_o,LE_m,LE_f,LE_fΔm,HALE_o,HALE_m,HALE_f,HALE_fΔm,ratio_o,ratio_m,ratio_f,choice_1,choice_2
,,,,,,,,,,,,,,
China,1455351282,77.31,74.58,80.36,5.78,68.45,66.99,70.08,3.09,88.54,89.82,87.21,ase,ase
India,1389030312,70.73,69.18,72.41,3.23,60.88,60.70,61.08,0.38,86.07,87.74,84.35,ass,ass
USA,337790067,78.74,76.53,80.98,4.45,66.02,65.13,66.93,1.80,83.85,85.10,82.65,na,nam

In [32]:
def create_svg(df, regions, colors, box_width=147, box_height=236, file_name='le_diagram_WHO -test.svg', lang='en'):
    outs = {k: '' for k in regions.keys()}

    out_defs = out_graph = ''

    for i in range(len(df)):
        # extract single values for country
        population, le_o, le_m, le_f, le_fΔm, \
                    hale_o, hale_m, hale_f, hale_fΔm, \
                    ratio_o, ratio_m, ratio_f, region, x_text, y_text, text_anchor = df.iloc[i]
        # ratio_o = round(ratio_o, 1)
        # ratio_m = round(ratio_m, 1)
        # ratio_f = round(ratio_f, 1)
        
        name = df.iloc[i].name

        # transtlate name of country to Russian if this is required
        name = dd_to_rus[name] if lang=='ru' else name

        x = int(le_m * 10)
        y = int(le_f * -10)
        radius = round(population ** (1/2) / 800, 2)
        color = colors[region]

        if pd.notna(text_anchor):  # if there is label for country
            out_label_defs = f'\n      <text x="{x_text}" y="{y_text}" dy="0.7ex" text-anchor="{text_anchor}" stroke="none">{name}</text>'
            out_label_active = "";
        else:
            x_text = int(x - radius * 0.8);
            y_text = int(y - radius * 0.8);
            out_label_defs = "";
            out_label_active = f'\n      <text x="{x_text}" y="{y_text}" dy="0.7ex" class="hidden_text" stroke="{color}">{name}</text>'

        population = f"{population:,}".replace(',', ' ')

        out_defs += (
            f'\n    <g id="bubble_{i}" fill="{color}">{out_label_defs}'
            f'\n      <circle cx="{x}" cy="{y}" r="1"/>'
            f'\n      <circle cx="{x}" cy="{y}" r="{radius}" stroke="{color}" fill="url(#grad_{region})"/>'
            f'\n    </g>')

        out_graph += \
            f'\n    <g class="active">' + \
            f'\n      <use xlink:href="#bubble_{i}"/>{out_label_active}' + \
           (f'\n      <title>{dd_decryption.get(name, name)}\n\nОжидаемая продолжительность жизни:\nмужчины:\t{le_m:.2f}\nобщая:\t\t{le_o:.2f}\nженщины:\t{le_f:.2f}' + \
            f'\n\nОжидаемая продолжительность здоровой жизни:\nмужчины:\t{hale_m:.2f}\t({ratio_m:.1f}% от ОПЖ)\nобщая:\t\t{hale_o:.2f}\t({ratio_o:.1f}% от ОПЖ)\nженщины:\t{hale_f:.2f}\t({ratio_f:.1f}% от ОПЖ)' + \
            f'\n\nНаселение: {population}</title>'
                if lang=='ru' else
            f'\n      <title>{dd_decryption.get(name, name)}\n\nLife Expectancy:\nmale:\t{le_m:.2f}\noverall:\t{le_o:.2f}\nfemale:\t{le_f:.2f}' + \
            f'\n\nHealthy Life Expectancy (HALE):\nmale:\t{hale_m:.2f}    ({ratio_m:.1f}% from LE)\noverall:\t{hale_o:.2f}    ({ratio_o:.1f}% from LE)\nfemale:\t{hale_f:.2f}    ({ratio_f:.1f}% from LE)' + \
            f'\n\nPopulation: {population}</title>') + \
            f'\n    </g>'
        
        outs[region] += f'\n        <use xlink:href="#bubble_{i}"/>'

    ##########
    out_grad = out_legend = ''
    y = -886

    for abbr in regions.keys():
        color = colors[abbr]
        region = regions[abbr]
        
        # transtlate name of region to Russian if this is required
        region = dd_to_rus[region] if lang=='ru' else region

        out_grad += (
            f'\n    <radialGradient id="grad_{abbr}" cx="50%" cy="50%" r="50%" fx="25%" fy="25%">'
            f'\n      <stop offset="50%" stop-color="{color}" stop-opacity="0"/>'
            f'\n      <stop offset="70%" stop-color="{color}" stop-opacity="0.05"/>'
            f'\n      <stop offset="99%" stop-color="{color}" stop-opacity="0.25"/>'
            f'\n    </radialGradient>')

        x = y + 5
        out_legend += (
            f'\n      <g class="active">'
            f'\n        <text x="425" y="{x}" fill="{color}">{region}</text>'
            f'\n        <circle cx="415" cy="{y}" r="8" fill="url(#grad_{abbr})"/>'
            f'\n        <circle cx="415" cy="{y}" r="1" fill="{color}"/>'
            + outs[abbr] +
            f'\n      </g>')

        y += 18

    #######
    out_ticks = ''

    for tick in range(45, 91, 5):
        x = tick * 10
        out_ticks += f'\n        <text x="{x}" y="-483">{tick}</text>'

    for tick in range(50, 91, 5):
        y = tick * -10 + 6
        out_ticks += f'\n        <text x="385" y="{y}">{tick}</text>'

    ######
    svg_code = """<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="350 -908 560 445">
  <title>Comparison gender life expectancy WHO-2019</title>
  <desc>Comparison of countries by life expectancy at birth according to estimation of the World Health Organization for 2019 (https://apps.who.int/gho/data/node.main.688). Squares of bubles are proportional to the population of countries, according to estimation of the United Nations for 2019 (https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_Population/WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx). Grouping of countries to subregions is according to the classification of the United Nations. Code of the program for creation of this chart: https://github.com/Lady3mlnm/Mini-programs-for-calculation-of-life-expectancy-in-countries/tree/main/SVG-diagrams-world.</desc>
  <style type="text/css">
    #main         { font-family:Helvetica,Arial,sans-serif; font-size:14px; text-anchor:middle;
                    stroke-opacity:0; fill-opacity:0.5; cursor:default; }
    #main:hover   { stroke-opacity:0; fill-opacity:0.1; }
    .nofade,
    .active:hover { stroke-opacity:1; fill-opacity:1; }
    .hidden_text  { font-size:14px; text-anchor:end; fill:none; pointer-events:none; }
  </style>
  <defs>

    <!-- determine appearance of circles -->""" + \
    out_grad + \
    """

    <!-- determine each country -->""" + \
    out_defs + \
    """

    <!-- vertical grid -->
    <path id="grid_x" d="M 0 -500 V -900"/>
    <g id="grid_x_5">
      <use xlink:href="#grid_x"/>
      <use xlink:href="#grid_x" transform="translate(10,0)"/>
      <use xlink:href="#grid_x" transform="translate(20,0)"/>
      <use xlink:href="#grid_x" transform="translate(30,0)"/>
      <use xlink:href="#grid_x" transform="translate(40,0)"/>
      <use xlink:href="#grid_x" transform="translate(50,0)"/>
    </g>

    <!-- horizontal grid -->
    <path id="grid_y" d="M 400 0 H 900"/>
    <g id="grid_y_5">
      <use xlink:href="#grid_y"/>
      <use xlink:href="#grid_y" transform="translate(0,-10)"/>
      <use xlink:href="#grid_y" transform="translate(0,-20)"/>
      <use xlink:href="#grid_y" transform="translate(0,-30)"/>
      <use xlink:href="#grid_y" transform="translate(0,-40)"/>
      <use xlink:href="#grid_y" transform="translate(0,-50)"/>
    </g>
  </defs>



  <g id="main">
    <g class="nofade">
      <!-- background for the whole diagram -->
      <circle cx="0" cy="0" r="99999" fill="#ffffff"/>

      <!-- draw grid -->
      <g stroke-opacity="0.05" stroke="#000000">
        <use xlink:href="#grid_x_5" transform="translate(400,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(450,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(500,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(550,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(600,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(650,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(700,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(750,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(800,0)"/>
        <use xlink:href="#grid_x_5" transform="translate(850,0)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-500)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-550)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-600)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-650)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-700)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-750)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-800)"/>
        <use xlink:href="#grid_y_5" transform="translate(0,-850)"/>
      </g>

      <!-- labels for axes -->
      <g fill="#999999">  <!-- color of font -->""" + \
    ("""
        <text x="650" y="-467" style="font-size: 12px">Ожидаемая при рождении продолжительность жизни для мужчин</text>
        <text transform="rotate(-90)" x="695" y="365" style="font-size: 12px">Ожидаемая при рождении продолжительность жизни для женщин</text>""" if lang=='ru' else 
     """
        <text x="650" y="-467">Male life expectancy at birth in years</text>
        <text transform="rotate(-90)" x="705" y="365">Female life expectancy at birth in years</text>""") + \
        out_ticks + \
    """
      </g>

      <!-- diagonal line -->
      <path d="M 500 -500 L 900 -900" stroke="#00cc00" stroke-width="0.8" stroke-opacity="0.4"/>
    </g>

    <!-- menu -->
    <g text-anchor="start">

      <!-- rectangle around items -->
      <rect class="nofade" x="403" y="-896" width=\"""" + str(box_width) + """\" height=\"""" + str(box_height) + """\" rx="5" ry="5" stroke="#999999" fill="#ffffff"/>

      <!-- single items -->""" + \
      out_legend + \
    """
    </g>

    <!-- pop-up notes -->""" + \
    out_graph + \
    """
  </g>
</svg>"""

    with open('output-interactive_svg/' + file_name, 'w', encoding="utf-8") as fh:
        fh.write(svg_code)
              
    print(f"Done. Number of processed countries: {len(df)}")

<br />
<br />
<br />

In [34]:
# Statistics for the world, excluding countries with population less than 1_000_000
df_selected = df[df['pop'] >= 1_000_000]  \
              .drop(columns='choice_2')   \
              .rename(columns={'choice_1': 'region'})

df_selected.loc['South Korea', ['label_x', 'label_y', 'label_position']] = (797, -885, 'end')
df_selected.loc['France', ['label_x', 'label_y', 'label_position']] = (785, -871, 'end')
df_selected.loc['Germany', ['label_x', 'label_y', 'label_position']] = (770, -860, 'end')
df_selected.loc['China', ['label_x', 'label_y', 'label_position']] = (708, -849, 'end')
df_selected.loc['Mexico', ['label_x', 'label_y', 'label_position']] = (696, -833, 'end')
df_selected.loc['Brazil', ['label_x', 'label_y', 'label_position']] = (692, -819, 'end')
df_selected.loc['Vietnam', ['label_x', 'label_y', 'label_position']] = (682, -805, 'end')
df_selected.loc['Russia', ['label_x', 'label_y', 'label_position']] = (661, -790, 'end')
df_selected.loc['Ukraine', ['label_x', 'label_y', 'label_position']] = (661, -773, 'end')
df_selected.loc['Mongolia', ['label_x', 'label_y', 'label_position']] = (643, -755, 'end')
df_selected.loc['Philippines', ['label_x', 'label_y', 'label_position']] = (632, -738, 'end')
df_selected.loc['Uganda', ['label_x', 'label_y', 'label_position']] = (620, -715, 'end')
df_selected.loc['Congo DR', ['label_x', 'label_y', 'label_position']] = (576, -651, 'end')
df_selected.loc['Mozambique', ['label_x', 'label_y', 'label_position']] = (531, -618, 'end')
df_selected.loc['Somalia', ['label_x', 'label_y', 'label_position']] = (512, -580, 'end')

df_selected.loc['Japan', ['label_x', 'label_y', 'label_position']] = (827, -890, 'start')
df_selected.loc['Spain', ['label_x', 'label_y', 'label_position']] = (833, -854, 'start')
df_selected.loc['Australia', ['label_x', 'label_y', 'label_position']] = (827, -840, 'start')
df_selected.loc['Canada', ['label_x', 'label_y', 'label_position']] = (820, -826, 'start')
df_selected.loc['UAE', ['label_x', 'label_y', 'label_position']] = (814, -812, 'start')
df_selected.loc['UK', ['label_x', 'label_y', 'label_position']] = (804, -797, 'start')
df_selected.loc['USA', ['label_x', 'label_y', 'label_position']] = (798, -782, 'start')
df_selected.loc['Saudi Arabia', ['label_x', 'label_y', 'label_position']] = (791, -766, 'start')
df_selected.loc['Algeria', ['label_x', 'label_y', 'label_position']] = (765, -751, 'start')
df_selected.loc['Bangladesh', ['label_x', 'label_y', 'label_position']] = (752, -738, 'start')
df_selected.loc['Morocco', ['label_x', 'label_y', 'label_position']] = (748, -724, 'start')
df_selected.loc['Indonesia', ['label_x', 'label_y', 'label_position']] = (748, -710, 'start')
df_selected.loc['India', ['label_x', 'label_y', 'label_position']] = (740, -690, 'start')
df_selected.loc['Ethiopia', ['label_x', 'label_y', 'label_position']] = (686, -668, 'start')
df_selected.loc['Pakistan', ['label_x', 'label_y', 'label_position']] = (675, -653, 'start')
df_selected.loc['Haiti', ['label_x', 'label_y', 'label_position']] = (650, -640, 'start')
df_selected.loc['Nigeria', ['label_x', 'label_y', 'label_position']] = (645, -624, 'start')
df_selected.loc['Afghanistan', ['label_x', 'label_y', 'label_position']] = (616, -608, 'start')
df_selected.loc['Chad', ['label_x', 'label_y', 'label_position']] = (582, -597, 'start')

ls_selected = ['euw', 'eun', 'eus', 'eue', 'asc', 'asw', 'ass', 'ase', 'asse', 'oc', 'na', 'sa', 'af']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=236, file_name='Comparison of male and female life expectancy -world.svg', lang='en')

Done. Number of processed countries: 157

In [35]:
df_selected.loc['Brazil', ['label_x', 'label_y', 'label_position']] = (None, None, None)
df_selected.loc['Vietnam', ['label_x', 'label_y', 'label_position']] = (None, None, None)
df_selected.loc['Morocco', ['label_x', 'label_y', 'label_position']] = (None, None, None)
df_selected.loc['Algeria', ['label_x', 'label_y', 'label_position']] = (None, None, None)
df_selected.loc['Mexico', ['label_x', 'label_y', 'label_position']] = (None, None, None)

df_selected.loc['Poland', ['label_x', 'label_y', 'label_position']] = (708, -849, 'end')
df_selected.loc['China', ['label_x', 'label_y', 'label_position']] = (696, -833, 'end')
df_selected.loc['Belarus', ['label_x', 'label_y', 'label_position']] = (692, -820, 'end')
df_selected.loc['Russia', ['label_x', 'label_y', 'label_position']] = (686, -805, 'end')
df_selected.loc['Kazakhstan', ['label_x', 'label_y', 'label_position']] = (661, -790, 'end')
df_selected.loc['Ukraine', ['label_x', 'label_y', 'label_position']] = (661, -773, 'end')
df_selected.loc['Philippines', ['label_x', 'label_y', 'label_position']] = (639, -738, 'end')
df_selected.loc['Congo DR', ['label_x', 'label_y', 'label_position']] = (576, -648, 'end')

df_selected.loc['Uzbekistan', ['label_x', 'label_y', 'label_position']] = (748, -724, 'start')
df_selected.loc['UK', ['label_x', 'label_y', 'label_position']] = (805, -797, 'start')
df_selected.loc['USA', ['label_x', 'label_y', 'label_position']] = (797, -782, 'start')
df_selected.loc['Turkey', ['label_x', 'label_y', 'label_position']] = (791, -766, 'start')
df_selected.loc['Saudi Arabia', ['label_x', 'label_y', 'label_position']] = (765, -751, 'start')

create_svg(df_selected, regions, colors, box_width=158, box_height=236, file_name='Comparison of male and female life expectancy -world -ru.svg', lang='ru')

Done. Number of processed countries: 157

<br />
<br />
<br />

In [37]:
# Statistics for Europe
additional_countries = ['Armenia', 'Azerbaijan', 'Cyprus', 'Georgia', 'Kazakhstan', 'Turkey']

df_selected = df[df['choice_2'].isin(['euw', 'eun', 'eus', 'eue']) | (df.index.isin(additional_countries))]  \
              .drop(columns='choice_1')   \
              .rename(columns={'choice_2': 'region'})

df_selected.loc[additional_countries, 'region'] = '-'

df_selected.loc['France', ['label_x', 'label_y', 'label_position']] = (790, -873, 'end')
df_selected.loc['Portugal', ['label_x', 'label_y', 'label_position']] = (769, -860, 'end')
df_selected.loc['Germany', ['label_x', 'label_y', 'label_position']] = (764, -846, 'end')
df_selected.loc['Poland', ['label_x', 'label_y', 'label_position']] = (720, -832, 'end')
df_selected.loc['Romania', ['label_x', 'label_y', 'label_position']] = (701, -819, 'end')
df_selected.loc['Belarus', ['label_x', 'label_y', 'label_position']] =  (686, -805, 'end')
df_selected.loc['Russia', ['label_x', 'label_y', 'label_position']] = (661, -790, 'end')
df_selected.loc['Ukraine', ['label_x', 'label_y', 'label_position']] = (661, -773, 'end')

df_selected.loc['Spain', ['label_x', 'label_y', 'label_position']] = (798, -881, 'start')
df_selected.loc['Switzerland', ['label_x', 'label_y', 'label_position']] = (830, -868, 'start')
df_selected.loc['Italy', ['label_x', 'label_y', 'label_position']] = (834, -854, 'start')
df_selected.loc['Sweden', ['label_x', 'label_y', 'label_position']] = (829, -840, 'start')
df_selected.loc['Netherlands', ['label_x', 'label_y', 'label_position']] = (822, -827, 'start')
df_selected.loc['Belgium', ['label_x', 'label_y', 'label_position']] = (813, -812, 'start')
df_selected.loc['UK', ['label_x', 'label_y', 'label_position']] = (803, -797, 'start')
df_selected.loc['Turkey', ['label_x', 'label_y', 'label_position']] = (783, -784, 'start')
df_selected.loc['Serbia', ['label_x', 'label_y', 'label_position']] = (753, -772, 'start')

ls_selected = ['euw', 'eun', 'eus', 'eue', '-']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=96, file_name='Comparison of male and female life expectancy -Europe.svg', lang='en')

Done. Number of processed countries: 45

In [38]:
# additional sub-diagram of European countries that are in the European Union
ls_countries_in_EU = ['Germany', 'UK', 'France', 'Italy', 'Spain', 'Poland', 'Romania', 'Netherlands', 'Belgium', 'Czechia', 'Sweden',
                      'Greece', 'Portugal', 'Hungary', 'Austria', 'Bulgaria', 'Denmark', 'Finland', 'Slovakia',
                      'Ireland', 'Croatia', 'Lithuania', 'Slovenia', 'Latvia', 'Estonia', 'Luxembourg', 'Malta', 'Cyprus']

df_selected_EU = df_selected.loc[ls_countries_in_EU]
print(f"Number of countries in dataFrame for the European Union: {len(df_selected_EU)}")
create_svg(df_selected_EU, regions, colors, box_width=147, box_height=96, file_name='Comparison of male and female life expectancy -European Union.svg', lang='en')

Number of countries in dataFrame for the European Union: 28
Done. Number of processed countries: 28

In [39]:
df_selected.loc['Turkey', ['label_x', 'label_y', 'label_position']] = (784, -785, 'start')
df_selected.loc['Kazakhstan', ['label_x', 'label_y', 'label_position']] = (743, -756, 'start')

create_svg(df_selected, regions, colors, box_width=147, box_height=96, file_name='Comparison of male and female life expectancy -Europe -ru.svg', lang='ru')

Done. Number of processed countries: 45

In [40]:
create_svg(df_selected_EU, regions, colors, box_width=147, box_height=96, file_name='Comparison of male and female life expectancy -European Union -ru.svg', lang='ru')

Done. Number of processed countries: 28

<br />
<br />
<br />

In [42]:
# Statistics for Asia
additional_countries = ['Russia', 'Egypt']

df_selected = df[df['choice_2'].isin(['asc', 'asw', 'ass', 'ase', 'asse', 'oc']) | (df.index.isin(additional_countries))]  \
              .drop(columns='choice_1')   \
              .rename(columns={'choice_2': 'region'})

df_selected.loc[additional_countries, 'region'] = '-'

df_selected.loc['South Korea', ['label_x', 'label_y', 'label_position']] = (792, -878, 'end')
df_selected.loc['Kuwait', ['label_x', 'label_y', 'label_position']] = (784, -862, 'end')
df_selected.loc['China', ['label_x', 'label_y', 'label_position']] = (710, -849, 'end')
df_selected.loc['Thailand', ['label_x', 'label_y', 'label_position']] = (696, -834, 'end')
df_selected.loc['Vietnam', ['label_x', 'label_y', 'label_position']] = (692, -819, 'end')
df_selected.loc['Russia', ['label_x', 'label_y', 'label_position']] = (687, -805, 'end')
df_selected.loc['Kazakhstan', ['label_x', 'label_y', 'label_position']] = (661, -790, 'end')
df_selected.loc['Iraq', ['label_x', 'label_y', 'label_position']] = (661, -773, 'end')
df_selected.loc['Philippines', ['label_x', 'label_y', 'label_position']] = (632, -738, 'end')
df_selected.loc['Mongolia', ['label_x', 'label_y', 'label_position']] = (645, -755, 'end')
df_selected.loc['Myanmar', ['label_x', 'label_y', 'label_position']] = (630, -718, 'end')
df_selected.loc['Yemen', ['label_x', 'label_y', 'label_position']] = (615, -695, 'end')

df_selected.loc['Japan', ['label_x', 'label_y', 'label_position']] = (827, -890, 'start')
df_selected.loc['Singapore', ['label_x', 'label_y', 'label_position']] = (838, -869, 'start')
df_selected.loc['Australia', ['label_x', 'label_y', 'label_position']] = (834, -854, 'start')
df_selected.loc['Israel', ['label_x', 'label_y', 'label_position']] = (828, -840, 'start')
df_selected.loc['Cyprus', ['label_x', 'label_y', 'label_position']] = (822, -827, 'start')
df_selected.loc['New Zealand', ['label_x', 'label_y', 'label_position']] = (816, -812, 'start')
df_selected.loc['UAE', ['label_x', 'label_y', 'label_position']] = (806, -797, 'start')
df_selected.loc['Iran', ['label_x', 'label_y', 'label_position']] = (801, -782, 'start')
df_selected.loc['Turkey', ['label_x', 'label_y', 'label_position']] = (791, -766, 'start')
df_selected.loc['Saudi Arabia', ['label_x', 'label_y', 'label_position']] = (766, -751, 'start')
df_selected.loc['Bangladesh', ['label_x', 'label_y', 'label_position']] = (752, -738, 'start')
df_selected.loc['Uzbekistan', ['label_x', 'label_y', 'label_position']] = (748, -724, 'start')
df_selected.loc['Indonesia', ['label_x', 'label_y', 'label_position']] = (748, -710, 'start')
df_selected.loc['India', ['label_x', 'label_y', 'label_position']] = (738, -690, 'start')
df_selected.loc['Pakistan', ['label_x', 'label_y', 'label_position']] = (685, -660, 'start')
df_selected.loc['Afghanistan', ['label_x', 'label_y', 'label_position']] = (640, -625, 'start')

ls_selected = ['asc', 'asw', 'ass', 'ase', 'asse', 'oc', '-']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=128, file_name='Comparison of male and female life expectancy -Asia.svg', lang='en')

Done. Number of processed countries: 59

In [43]:
create_svg(df_selected, regions, colors, box_width=159, box_height=128, file_name='Comparison of male and female life expectancy -Asia -ru.svg', lang='ru')

Done. Number of processed countries: 59

<br />
<br />
<br />

In [45]:
# Statistics for post-Soviet countries
ls_countries_in_USSR = \
    ['Armenia', 'Azerbaijan', 'Belarus', 'Estonia', 'Georgia', 'Kazakhstan', 'Kyrgyzstan', 'Latvia',
     'Lithuania', 'Moldova', 'Russia', 'Tajikistan', 'Turkmenistan', 'Ukraine', 'Uzbekistan']

df_selected = df[df['choice_2'].isin(['eun', 'eue', 'asw', 'asc'])]  \
              .drop(columns='choice_1')   \
              .rename(columns={'choice_2': 'region'}) \
              .loc[ls_countries_in_USSR]

print(f"Number of post-Soviet countries: {len(df_selected)}")

df_selected.loc['Estonia', ['label_x', 'label_y', 'label_position']] =  (710, -850, 'end')
df_selected.loc['Lithuania', ['label_x', 'label_y', 'label_position']] = (695, -835, 'end')
df_selected.loc['Latvia', ['label_x', 'label_y', 'label_position']] = (680, -820, 'end')

df_selected.loc['Belarus', ['label_x', 'label_y', 'label_position']] =  (650, -805, 'end')
df_selected.loc['Moldova', ['label_x', 'label_y', 'label_position']] = (650, -790, 'end')
df_selected.loc['Russia', ['label_x', 'label_y', 'label_position']] = (650, -775, 'end')
df_selected.loc['Ukraine', ['label_x', 'label_y', 'label_position']] = (650, -760, 'end')

df_selected.loc['Azerbaijan', ['label_x', 'label_y', 'label_position']] = (802, -795, 'start')
df_selected.loc['Armenia', ['label_x', 'label_y', 'label_position']] = (788, -781, 'start')
df_selected.loc['Georgia', ['label_x', 'label_y', 'label_position']] = (774, -767, 'start')
df_selected.loc['Tajikistan', ['label_x', 'label_y', 'label_position']] = (759, -752, 'start')
df_selected.loc['Kyrgyzstan', ['label_x', 'label_y', 'label_position']] = (745, -738, 'start')
df_selected.loc['Kazakhstan', ['label_x', 'label_y', 'label_position']] = (729, -722, 'start')
df_selected.loc['Uzbekistan', ['label_x', 'label_y', 'label_position']] = (713, -708, 'start')
df_selected.loc['Turkmenistan', ['label_x', 'label_y', 'label_position']] = (700, -693, 'start')

ls_selected = ['eun', 'eue', 'asw', 'asc']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=76, file_name='Comparison of male and female life expectancy -post-USSR.svg', lang='en')

Number of post-Soviet countries: 15
Done. Number of processed countries: 15

In [46]:
create_svg(df_selected, regions, colors, box_width=147, box_height=76, file_name='Comparison of male and female life expectancy -post-USSR -ru.svg', lang='ru')

Done. Number of processed countries: 15

<br />
<br />
<br />

In [48]:
# Statistics for America
df_selected = df[df['choice_2'].isin(['nam', 'ca', 'car', 'sa'])]  \
              .drop(columns='choice_1')   \
              .rename(columns={'choice_2': 'region'})

df_selected.loc['Canada', ['label_x', 'label_y', 'label_position']] = (835, -861, 'end')
df_selected.loc['Costa Rica', ['label_x', 'label_y', 'label_position']] = (754, -844, 'end')
df_selected.loc['Puerto Rico', ['label_x', 'label_y', 'label_position']] = (774, -859, 'end')
df_selected.loc['Cuba', ['label_x', 'label_y', 'label_position']] = (732, -830, 'end')
df_selected.loc['Mexico', ['label_x', 'label_y', 'label_position']] = (707, -819, 'end')
df_selected.loc['Brazil', ['label_x', 'label_y', 'label_position']] = (694, -805, 'end')
df_selected.loc['Dominican Republic', ['label_x', 'label_y', 'label_position']] = (674, -786, 'end')
df_selected.loc['Venezuela', ['label_x', 'label_y', 'label_position']] = (673, -765, 'end')
df_selected.loc['Guatemala', ['label_x', 'label_y', 'label_position']] = (670, -750, 'end')
df_selected.loc['Honduras', ['label_x', 'label_y', 'label_position']] = (670, -735, 'end')
df_selected.loc['Haiti', ['label_x', 'label_y', 'label_position']] = (621, -651, 'end')

df_selected.loc['Chile', ['label_x', 'label_y', 'label_position']] = (820, -814, 'start')
df_selected.loc['USA', ['label_x', 'label_y', 'label_position']] = (807, -801, 'start')
df_selected.loc['Peru', ['label_x', 'label_y', 'label_position']] = (792, -785, 'start')
df_selected.loc['Argentina', ['label_x', 'label_y', 'label_position']] = (773, -768, 'start')


ls_selected = ['nam', 'ca', 'car', 'sa']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=76, file_name='Comparison of male and female life expectancy -America.svg', lang='en')

Done. Number of processed countries: 34

In [49]:
create_svg(df_selected, regions, colors, box_width=171, box_height=76, file_name='Comparison of male and female life expectancy -America -ru.svg', lang='ru')

Done. Number of processed countries: 34

In [50]:
# additional sub-diagram of Latin American countries
ls_countries_Latin_America = \
    ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Costa Rica', 'Cuba',
     'Dominican Republic', 'Ecuador', 'El Salvador', 'Guatemala', 'Haiti', 'Honduras',
     'Mexico', 'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Puerto Rico', 'Uruguay', 'Venezuela']

df_selected_Latin_America = df_selected.loc[ls_countries_Latin_America]
print(f"Number of countries in dataFrame for Latin America: {len(df_selected_Latin_America)}")

ls_selected = ['ca', 'car', 'sa']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}
create_svg(df_selected_Latin_America, regions, colors, box_width=147, box_height=57, file_name='Comparison of male and female life expectancy -Latin America.svg', lang='en')

Number of countries in dataFrame for Latin America: 21
Done. Number of processed countries: 21

In [51]:
create_svg(df_selected_Latin_America, regions, colors, box_width=171, box_height=57, file_name='Comparison of male and female life expectancy -Latin America -ru.svg', lang='ru')

Done. Number of processed countries: 21

<br />
<br />
<br />

In [53]:
# Statistics for Africa
df_selected = df[df['choice_2'].isin(['afn', 'afw', 'afm', 'afe', 'afs'])]  \
              .drop(columns='choice_1')   \
              .rename(columns={'choice_2': 'region'})

df_selected.loc['Tunisia', ['label_x', 'label_y', 'label_position']] = (735, -805, 'end')
df_selected.loc['Cape Verde', ['label_x', 'label_y', 'label_position']] = (689, -796, 'end')
df_selected.loc['Mauritius', ['label_x', 'label_y', 'label_position']] = (683, -781, 'end')
df_selected.loc['Seychelles', ['label_x', 'label_y', 'label_position']] = (683, -767, 'end')
df_selected.loc['Egypt', ['label_x', 'label_y', 'label_position']] = (670, -748, 'end')
df_selected.loc['Rwanda', ['label_x', 'label_y', 'label_position']] = (652, -725, 'end')
df_selected.loc['Uganda', ['label_x', 'label_y', 'label_position']] = (613, -706, 'end')
df_selected.loc['South Africa', ['label_x', 'label_y', 'label_position']] = (590, -690, 'end')
df_selected.loc['Angola', ['label_x', 'label_y', 'label_position']] = (582, -665, 'end')
df_selected.loc['Congo DR', ['label_x', 'label_y', 'label_position']] = (576, -648, 'end')
df_selected.loc['Mozambique', ['label_x', 'label_y', 'label_position']] = (535, -625, 'end')
df_selected.loc['Eswatini', ['label_x', 'label_y', 'label_position']] = (510, -600, 'end')
df_selected.loc['Somalia', ['label_x', 'label_y', 'label_position']] = (512, -582, 'end')
df_selected.loc['CAR', ['label_x', 'label_y', 'label_position']] = (490, -564, 'end')
df_selected.loc['Lesotho', ['label_x', 'label_y', 'label_position']] = (467, -545, 'end')

df_selected.loc['Algeria', ['label_x', 'label_y', 'label_position']] = (778, -767, 'start')
df_selected.loc['Morocco', ['label_x', 'label_y', 'label_position']] = (760, -749, 'start')
df_selected.loc['Libya', ['label_x', 'label_y', 'label_position']] = (742, -733, 'start')
df_selected.loc['Sudan', ['label_x', 'label_y', 'label_position']] = (713, -705, 'start')
df_selected.loc['Ethiopia', ['label_x', 'label_y', 'label_position']] = (697, -688, 'start')
df_selected.loc['Tanzania', ['label_x', 'label_y', 'label_position']] = (682, -671, 'start')
df_selected.loc['Nigeria', ['label_x', 'label_y', 'label_position']] = (665, -654, 'start')
df_selected.loc['Congo Republic', ['label_x', 'label_y', 'label_position']] = (646, -635, 'start')
df_selected.loc['Niger', ['label_x', 'label_y', 'label_position']] = (626, -615, 'start')
df_selected.loc['Chad', ['label_x', 'label_y', 'label_position']] = (587, -597, 'start')


ls_selected = ['afn', 'afw', 'afm', 'afe', 'afs']
regions = {k:regions_all[k] for k in ls_selected}
colors = {k:colors_all[k] for k in ls_selected}

create_svg(df_selected, regions, colors, box_width=147, box_height=96, file_name='Comparison of male and female life expectancy -Africa.svg', lang='en')

Done. Number of processed countries: 54

In [54]:
create_svg(df_selected, regions, colors, box_width=167, box_height=96, file_name='Comparison of male and female life expectancy -Africa -ru.svg', lang='ru')

Done. Number of processed countries: 54