[List of British regions by life expectancy](https://en.wikipedia.org/wiki/List_of_British_regions_by_life_expectancy) / 
[Продолжительность жизни в регионах Великобритании](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_регионах_Великобритании)

Data source: [2017–2019](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/bulletins/lifeexpectancyforlocalareasoftheuk/between2001to2003and2017to2019), [2022–2024](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandlifeexpectancies/bulletins/lifeexpectancyforlocalareasoftheuk/between2001to2003and2022to2024)

In [2]:
import pandas as pd
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [3]:
df_2019 = pd.read_csv('data/LE in regions of England in 2017-19.csv', engine='python', skiprows=6, skipfooter=5, header=None, index_col=0, usecols=[0,1,6])

# manually patch DataFrame with values for the United Kingdom on average
if 'United Kingdom' not in df_2019.index:
    df_2019.loc['United Kingdom'] = [79.4, 83.1]

df_2019.rename(index={'Yorkshire and The Humber': 'Yorkshire and the Humber'}, inplace=True)  #  'East of England': 'East'

df_2019.index.name = ''
df_2019.columns = ['2017-19_m', '2017-19_f']
df_2019['2017-19_fΔm'] = (df_2019['2017-19_f'] - df_2019['2017-19_m']).round(1)
df_2019['2017-19_mean'] = ((df_2019['2017-19_f'] + df_2019['2017-19_m']) / 2).round(2)
df_2019

                          2017-19_m  2017-19_f  2017-19_fΔm  2017-19_mean

England                        79.8       83.4          3.6         81.60
North East                     78.0       81.8          3.8         79.90
North West                     78.4       82.1          3.7         80.25
Yorkshire and the Humber       78.8       82.5          3.7         80.65
East Midlands                  79.5       82.9          3.4         81.20
West Midlands                  79.0       82.9          3.9         80.95
East of England                80.5       83.9          3.4         82.20
London                         80.9       84.7          3.8         82.80
South East                     80.8       84.3          3.5         82.55
South West                     80.4       84.1          3.7         82.25
Northern Ireland               78.8       82.6          3.8         80.70
Scotland                       77.2       81.1          3.9         79.15
Wales                          78.5       82.3          3.8         80.40
United Kingdom                 79.4       83.1          3.7         81.25

In [4]:
df_2024 = pd.read_excel('data/LE in regions of England in 2022-24 -figure 1 data.xlsx', skiprows=6, index_col=0, usecols=[0,1,4])

# df_2024.rename(index={'East': 'East of England'}, inplace=True)

df_2024.index.name = ''
df_2024.columns = ['2022-24_m', '2022-24_f']
df_2024['2022-24_fΔm'] = (df_2024['2022-24_f'] - df_2024['2022-24_m']).round(1)
df_2024['2022-24_mean'] = ((df_2024['2022-24_f'] + df_2024['2022-24_m']) / 2).round(2)
df_2024

                          2022-24_m  2022-24_f  2022-24_fΔm  2022-24_mean

England                        79.5       83.3          3.8         81.40
Northern Ireland               78.8       82.6          3.8         80.70
Scotland                       77.2       81.1          3.9         79.15
Wales                          78.3       82.2          3.9         80.25
United Kingdom                 79.2       83.0          3.8         81.10
North East                     77.7       81.6          3.9         79.65
North West                     77.9       81.9          4.0         79.90
Yorkshire and the Humber       78.3       82.3          4.0         80.30
East Midlands                  79.0       82.8          3.8         80.90
West Midlands                  78.7       82.8          4.1         80.75
East of England                80.3       84.0          3.7         82.15
London                         80.5       84.7          4.2         82.60
South East                     80.7       84.4          3.7         82.55
South West                     80.3       84.1          3.8         82.20

In [5]:
df = pd.concat([df_2019, df_2024], axis='columns')

df.insert(loc=4, column='Δ_in_mean', value=(df['2022-24_mean']-df['2017-19_mean']).round(2))

df.sort_values(by=['2017-19_mean', '2017-19_m'], ascending=False, inplace=True)

df.fillna('')

,2017-19_m,2017-19_f,2017-19_fΔm,2017-19_mean,Δ_in_mean,2022-24_m,2022-24_f,2022-24_fΔm,2022-24_mean
,,,,,,,,,
London,80.9,84.7,3.8,82.80,-0.20,80.5,84.7,4.2,82.60
South East,80.8,84.3,3.5,82.55,0.00,80.7,84.4,3.7,82.55
South West,80.4,84.1,3.7,82.25,-0.05,80.3,84.1,3.8,82.20
East of England,80.5,83.9,3.4,82.20,-0.05,80.3,84.0,3.7,82.15
England,79.8,83.4,3.6,81.60,-0.20,79.5,83.3,3.8,81.40
United Kingdom,79.4,83.1,3.7,81.25,-0.15,79.2,83.0,3.8,81.10
East Midlands,79.5,82.9,3.4,81.20,-0.30,79.0,82.8,3.8,80.90
West Midlands,79.0,82.9,3.9,80.95,-0.20,78.7,82.8,4.1,80.75
Northern Ireland,78.8,82.6,3.8,80.70,0.00,78.8,82.6,3.8,80.70
Yorkshire and the Humber,78.8,82.5,3.7,80.65,-0.35,78.3,82.3,4.0,80.30
Wales,78.5,82.3,3.8,80.40,-0.15,78.3,82.2,3.9,80.25
North West,78.4,82.1,3.7,80.25,-0.35,77.9,81.9,4.0,79.90
North East,78.0,81.8,3.8,79.90,-0.25,77.7,81.6,3.9,79.65
Scotland,77.2,81.1,3.9,79.15,0.00,77.2,81.1,3.9,79.15

<br />
<br />

In [7]:
# just for interest, explore results: determine regions with max and min values, and also look at specific regions
mal.min_and_max_values(df[['2017-19_mean', 'Δ_in_mean', '2022-24_mean', '2017-19_m', '2022-24_m', '2017-19_f', '2022-24_f', '2017-19_fΔm', '2022-24_fΔm']],                           
                           max_lng=10, row_center=['London', 'England', 'United Kingdom'])

Number of records: 14

In [8]:
# just for interest, explore difference between regions with max and min life expectancy
for period in ['2017-19_mean', '2022-24_mean']:
    print(f"{period}: {(df[[period]].max().iloc[0] - df[[period]].min().iloc[0]):.2f}")

2017-19_mean: 3.65
2022-24_mean: 3.45

<br />
<br />

In [10]:
# for region in sorted(df.index):
#     print(f"    '{region}' : {{'en': ('', ''), 'ru': ('', '')}},")

In [11]:
dd_replacement = {
    'England' : {'en': ('England on average', 'England'), 'ru': ('Англия в среднем', 'Англия')},
    'Northern Ireland' : {'en': ('Northern Ireland', 'Northern Ireland'), 'ru': ('Северная Ирландия', 'Северная Ирландия')},
    'Scotland' : {'en': ('Scotland', 'Scotland'), 'ru': ('Шотландия', 'Шотландия')},
    'Wales' : {'en': ('Wales', 'Wales'), 'ru': ('Уэльс', 'Уэльс')},
    'East of England' : {'en': ('East of England', 'East of England'), 'ru': ('Восточная Англия', 'Восточная Англия')},
    'East Midlands' : {'en': ('East Midlands', 'East Midlands'), 'ru': ('Восточный Ми́дленд', 'Восточный Мидленд')},
    'London' : {'en': ('London region', 'Greater London'), 'ru': ('Большой Ло́ндон', 'Большой Лондон')},
    'North East' : {'en': ('North East England', 'North East England'), 'ru': ('Северо-Восточная Англия', 'Северо-Восточная Англия')},
    'North West' : {'en': ('North West England', 'North West England'), 'ru': ('Северо-Западная Англия', 'Северо-Западная Англия')},
    'South East' : {'en': ('South East England', 'South East England'), 'ru': ('Юго-Восточная Англия', 'Юго-Восточная Англия')},
    'South West' : {'en': ('South West England', 'South West England'), 'ru': ('Юго-Западная Англия', 'Юго-Западная Англия')},
    'West Midlands' : {'en': ('West Midlands', 'West Midlands (region)'), 'ru': ('Западный Ми́дленд', 'Западный Мидленд')},
    'Yorkshire and the Humber' : {'en': ('Yorkshire and the Humber', 'Yorkshire and the Humber'), 'ru': ('Йо́ркшир и Ха́мбер', 'Йоркшир и Хамбер')},
    'United Kingdom' : {'en': ('United Kingdom', 'United Kingdom'), 'ru': ('Великобрита́ния ', 'Великобритания')}
}

In [24]:
# create code for placing info in Wikipedia
def create_table(df, file_header, lang='ru'):

    def if_value(x, prec=1):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=1, *, add_par=''):  # change_value
        return f'style="background:#fffae0;{add_par}"|—' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"|{x:0.{prec}f}' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"|−{-x:0.{prec}f}' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"|{x:0.{prec}f}'
    
    def chval_bold(x, prec=1, *, add_par=''):  # change_value
        return '—' if math.isnan(x) else \
               f'style="background:#fffae0;color:darkgreen;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="background:#fffae0;color:crimson;{add_par}"|\'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="background:#fffae0;color:darkgray;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\''
    
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]
        name_link = dd_replacement[ser.name][lang][1]
        name_visible = dd_replacement[ser.name][lang][0]
        name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"

        if ser.name in ['England', 'Northern Ireland', 'Scotland', 'Wales', 'United Kingdom']:
             st += '\n' + ('|-class=static-row-header\n' if ser.name in ['England', 'United Kingdom'] else '|-\n') + \
                  f'| \'\'\'[[{name_inserted}]]\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2017-19_m"], prec=1)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2017-19_f"], prec=1)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2017-19_fΔm"], prec=1)}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser["2017-19_mean"], prec=2)}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-right:3ex;"| \'\'\'{if_value(ser["Δ_in_mean"], prec=2)}\'\'\' ' + \
                  f'||style="background:#eaf3ff;border-left-width:2px;"| \'\'\'{if_value(ser["2022-24_m"], prec=1)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2022-24_f"], prec=1)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2022-24_fΔm"], prec=1)}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser["2022-24_mean"], prec=2)}\'\'\''
        else:
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2017-19_m"], prec=1)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2017-19_f"], prec=1)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2017-19_fΔm"], prec=1)} ' + \
                  f'|| {if_value(ser["2017-19_mean"], prec=2)} ' + \
                  f'||style="border-left-width:2px;padding-right:3ex;"| {if_value(ser["Δ_in_mean"], prec=2)} ' + \
                  f'||style="background:#eaf3ff;border-left-width:2px;"| {if_value(ser["2022-24_m"], prec=1)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2022-24_f"], prec=1)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2022-24_fΔm"], prec=1)} ' + \
                  f'|| {if_value(ser["2022-24_mean"], prec=2)}'
        
    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —')

    return st



table_code = create_table(df, file_header='UK_header-2024-en.txt', lang='en')
with open('output/Table code for British regions -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

table_code = create_table(df, file_header='UK_header-2024-ru.txt', lang='ru')
with open('output/Table code for British regions -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)