source of data: [Türkiye İstatistik Kurumu](https://data.tuik.gov.tr/Kategori/GetKategori?p=nufus-ve-demografi-109&dil=2), filter "Life expectancy at birth by provinces and sex" > "Life expectancy at birth by provinces and sex"<br>
[List of Turkish provinces by life expectancy](https://en.wikipedia.org/wiki/List_of_Turkish_provinces_by_life_expectancy)<br>
[Продолжительность жизни в провинциях Турции](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_провинциях_Турции)<br>
<br>
[Provinces of Turkey](https://en.wikipedia.org/wiki/Provinces_of_Turkey)<br>
[Türkiye'nin ilçeleri](https://tr.wikipedia.org/wiki/Türkiye'nin_ilçeleri)<br>
[Административное деление Турции](https://ru.wikipedia.org/wiki/Административное_деление_Турции)

In [1]:
import pandas as pd
import math
import re

In [2]:
pd.options.display.min_rows = 6
pd.options.display.max_rows = 60
pd.options.display.precision = 2

In [3]:
# load stats about longevity per year
df = pd.read_excel('data/Life expectancy in Turkey -2020.xls', skiprows=4, skipfooter=4) \
       .dropna(axis='columns', how='all')

df

,İller-Provinces,Toplam\nTotal,Erkek\nMale,Kadın\nFemale,Toplam\nTotal.1,Erkek\nMale.1,Kadın\nFemale.1,Toplam\nTotal.2,Erkek\nMale.2,Kadın\nFemale.2,Toplam\nTotal.3,Erkek\nMale.3,Kadın\nFemale.3
0,Türkiye-Türkiye,78.00,75.30,80.70,78.00,75.30,80.70,78.00,75.30,80.80,78.33,75.60,81.12
1,Adana,77.13,74.27,80.00,77.39,74.54,80.24,77.53,74.70,80.38,77.66,74.91,80.47
2,Adıyaman,79.57,76.25,82.91,79.55,76.57,82.49,79.71,77.27,82.12,79.29,76.94,81.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Kilis,74.93,71.87,78.00,74.95,72.26,77.64,76.14,72.87,79.55,76.09,73.47,78.83
80,Osmaniye,78.37,75.45,81.35,78.58,75.91,81.25,78.01,75.29,80.81,78.47,76.08,80.91
81,Düzce,78.07,75.29,80.93,77.75,75.01,80.57,77.49,74.49,80.69,78.04,75.19,81.06

In [4]:
df.columns = ['',
              '2013_total', '2013_male', '2013_female',
              '2013-14_total', '2013-14_male', '2013-14_female',
              '2015-17_total', '2015-17_male', '2015-17_female',
              '2018-20_total', '2018-20_male', '2018-20_female']

df = df.set_index('') \
       .rename(index={'Türkiye-Türkiye': 'Türkiye'})

df

,2013_total,2013_male,2013_female,2013-14_total,2013-14_male,2013-14_female,2015-17_total,2015-17_male,2015-17_female,2018-20_total,2018-20_male,2018-20_female
,,,,,,,,,,,,
Türkiye,78.00,75.30,80.70,78.00,75.30,80.70,78.00,75.30,80.80,78.33,75.60,81.12
Adana,77.13,74.27,80.00,77.39,74.54,80.24,77.53,74.70,80.38,77.66,74.91,80.47
Adıyaman,79.57,76.25,82.91,79.55,76.57,82.49,79.71,77.27,82.12,79.29,76.94,81.67
...,...,...,...,...,...,...,...,...,...,...,...,...
Kilis,74.93,71.87,78.00,74.95,72.26,77.64,76.14,72.87,79.55,76.09,73.47,78.83
Osmaniye,78.37,75.45,81.35,78.58,75.91,81.25,78.01,75.29,80.81,78.47,76.08,80.91
Düzce,78.07,75.29,80.93,77.75,75.01,80.57,77.49,74.49,80.69,78.04,75.19,81.06

In [5]:
# df.drop(columns=['2013_total', '2013_male', '2013_female'], inplace=True)
# df

In [6]:
df = df.loc[:, ['2015-17_total', '2015-17_male', '2015-17_female', '2018-20_total', '2018-20_male', '2018-20_female', ]]
df.columns = ['past_overall', 'past_male', 'past_female', 'overall', 'male', 'female', ]
df

          past_overall  past_male  past_female  overall   male  female

Türkiye          78.00      75.30        80.80    78.33  75.60   81.12
Adana            77.53      74.70        80.38    77.66  74.91   80.47
Adıyaman         79.71      77.27        82.12    79.29  76.94   81.67
...                ...        ...          ...      ...    ...     ...
Kilis            76.14      72.87        79.55    76.09  73.47   78.83
Osmaniye         78.01      75.29        80.81    78.47  76.08   80.91
Düzce            77.49      74.49        80.69    78.04  75.19   81.06

[82 rows x 6 columns]

In [7]:
df.insert(loc=3, column='past_f-m', value=df['past_female']-df['past_male'])
df.insert(loc=4, column='Δ_years', value=df['overall']-df['past_overall'])
df.insert(loc=8, column='f-m', value=df['female']-df['male'])
df

,past_overall,past_male,past_female,past_f-m,Δ_years,overall,male,female,f-m
,,,,,,,,,
Türkiye,78.00,75.30,80.80,5.50,0.33,78.33,75.60,81.12,5.52
Adana,77.53,74.70,80.38,5.67,0.13,77.66,74.91,80.47,5.56
Adıyaman,79.71,77.27,82.12,4.85,-0.42,79.29,76.94,81.67,4.73
...,...,...,...,...,...,...,...,...,...
Kilis,76.14,72.87,79.55,6.67,-0.05,76.09,73.47,78.83,5.37
Osmaniye,78.01,75.29,80.81,5.53,0.46,78.47,76.08,80.91,4.82
Düzce,77.49,74.49,80.69,6.20,0.55,78.04,75.19,81.06,5.87

In [8]:
pd.options.display.max_rows = 100
pd.options.display.precision = 3

def sort_df(df, by=['overall', 'male'], ascending=False):
    df.sort_values(by=by, ascending=ascending, inplace=True)
    indexes = df.index.to_list()
    ls_change_order = ['Türkiye']    # 'İstanbul'
    indexes = list(el for el in indexes if el not in ls_change_order)
    indexes = ls_change_order + indexes
    return df.reindex(indexes)
    
df = sort_df(df, by=['overall', 'male'])
df

,past_overall,past_male,past_female,past_f-m,Δ_years,overall,male,female,f-m
,,,,,,,,,
Türkiye,78.000,75.300,80.800,5.500,0.334,78.334,75.604,81.124,5.519
Gümüşhane,79.774,76.254,83.456,7.202,1.007,80.781,78.074,83.544,5.470
Muğla,80.278,77.591,83.179,5.587,0.424,80.702,77.748,83.964,6.217
Tunceli,80.690,77.409,84.248,6.838,-0.359,80.331,77.015,84.060,7.045
Trabzon,79.997,76.480,83.375,6.895,0.290,80.287,76.772,83.788,7.016
Ordu,79.295,76.177,82.561,6.384,0.746,80.041,77.229,82.974,5.745
Giresun,79.673,76.320,83.074,6.754,0.320,79.993,76.626,83.506,6.880
Antalya,79.298,76.663,82.114,5.451,0.436,79.734,77.262,82.380,5.119
Erzincan,79.186,76.072,82.472,6.400,0.418,79.605,76.913,82.344,5.430
Bolu,79.154,76.509,81.791,5.281,0.366,79.519,77.009,82.038,5.030
Artvin,79.349,76.268,82.646,6.378,0.113,79.461,76.371,82.748,6.378
Rize,79.009,74.821,83.183,8.363,0.389,79.398,75.549,83.274,7.724
Mardin,79.835,76.853,82.706,5.853,-0.511,79.324,76.728,81.837,5.109
Ankara,79.358,76.690,81.941,5.251,-0.065,79.293,76.546,82.015,5.469
Adıyaman,79.709,77.266,82.121,4.855,-0.419,79.290,76.941,81.666,4.726
Bayburt,79.076,76.259,82.189,5.930,0.140,79.216,77.047,81.405,4.358
Yalova,78.614,75.891,81.459,5.568,0.599,79.213,76.295,82.293,5.998
Bingöl,78.838,76.008,81.819,5.811,0.342,79.180,76.498,82.091,5.593
Burdur,79.170,76.100,82.280,6.180,-0.037,79.133,75.987,82.377,6.389
Iğdır,78.828,75.821,81.977,6.156,0.284,79.112,76.392,81.958,5.566
İstanbul,78.698,75.795,81.549,5.754,0.384,79.081,76.195,81.950,5.755
Karabük,78.400,75.375,81.553,6.178,0.669,79.068,76.236,81.998,5.763
Malatya,79.018,76.048,82.059,6.010,0.006,79.024,76.163,81.981,5.818
Amasya,78.466,75.723,81.258,5.535,0.525,78.991,76.295,81.758,5.464
İzmir,78.649,75.766,81.584,5.818,0.338,78.987,76.037,82.007,5.970
Mersin,78.230,75.493,81.063,5.570,0.679,78.908,76.327,81.579,5.252
Kahramanmaraş,79.241,77.041,81.527,4.486,-0.382,78.860,76.595,81.308,4.713
Çorum,78.634,75.903,81.474,5.571,0.212,78.845,76.203,81.571,5.369
Karaman,78.718,76.400,81.069,4.670,0.051,78.770,76.046,81.601,5.555
Elazığ,78.627,75.942,81.343,5.402,0.090,78.717,76.064,81.419,5.355
Isparta,78.696,76.089,81.325,5.236,-0.033,78.663,75.917,81.468,5.551
Çanakkale,77.994,75.133,81.016,5.883,0.658,78.652,75.562,81.947,6.386
Sinop,78.405,75.321,81.710,6.389,0.209,78.614,75.683,81.753,6.070
Aydın,78.528,75.466,81.756,6.290,0.042,78.569,75.541,81.778,6.237
Samsun,78.067,75.039,81.150,6.111,0.484,78.551,75.550,81.666,6.116
Eskişehir,77.983,75.240,80.780,5.540,0.559,78.541,75.839,81.292,5.453
Aksaray,78.317,75.675,80.880,5.204,0.191,78.509,75.520,81.513,5.993
Bartın,77.895,75.640,80.161,4.521,0.609,78.504,75.676,81.449,5.774
Batman,79.290,76.096,82.274,6.177,-0.808,78.482,75.369,81.544,6.175
Denizli,78.170,75.325,81.066,5.741,0.310,78.480,75.703,81.319,5.617
Diyarbakır,78.910,75.672,82.034,6.362,-0.431,78.479,75.481,81.511,6.030
Osmaniye,78.011,75.285,80.812,5.527,0.462,78.474,76.084,80.906,4.822
Sivas,77.970,75.418,80.650,5.232,0.489,78.459,75.910,81.162,5.252
Kocaeli,78.084,75.726,80.530,4.804,0.298,78.382,75.823,81.077,5.254
Şırnak,77.621,73.356,81.835,8.479,0.702,78.323,74.439,82.300,7.861
Niğde,77.629,74.686,80.605,5.919,0.673,78.302,75.360,81.278,5.918
Kayseri,77.870,75.306,80.445,5.139,0.369,78.238,75.661,80.862,5.200
Bursa,77.678,75.006,80.423,5.417,0.558,78.236,75.521,81.047,5.526
Zonguldak,77.810,75.116,80.488,5.372,0.391,78.201,75.480,80.962,5.482
Konya,78.326,75.763,80.858,5.096,-0.196,78.130,75.455,80.827,5.373
Tokat,77.520,74.944,80.160,5.216,0.567,78.087,75.525,80.750,5.225
Düzce,77.494,74.490,80.687,6.197,0.548,78.042,75.190,81.062,5.872
Kırklareli,77.675,74.637,80.958,6.321,0.359,78.034,74.947,81.374,6.428
Muş,77.452,74.708,80.098,5.390,0.581,78.033,75.443,80.644,5.201
Balıkesir,77.496,74.654,80.492,5.838,0.527,78.023,75.066,81.171,6.105
Siirt,78.370,75.239,81.399,6.160,-0.353,78.018,74.711,81.560,6.849
Kastamonu,77.360,74.511,80.317,5.806,0.657,78.016,75.026,81.162,6.137
Edirne,77.354,74.245,80.695,6.450,0.591,77.945,74.794,81.361,6.567
Kırıkkale,77.776,74.893,80.784,5.890,0.152,77.928,75.169,80.802,5.633
Nevşehir,77.847,75.454,80.173,4.719,0.064,77.910,75.033,80.827,5.794
Sakarya,77.506,74.789,80.338,5.548,0.346,77.852,75.162,80.691,5.528
Bilecik,77.829,74.994,80.770,5.777,0.017,77.846,75.356,80.465,5.110
Kırşehir,78.458,75.442,81.446,6.004,-0.616,77.841,74.895,80.774,5.880
Bitlis,78.396,75.642,81.063,5.420,-0.609,77.786,74.819,80.953,6.135
Çankırı,78.033,75.389,80.813,5.424,-0.253,77.780,75.172,80.564,5.392
Kars,77.344,75.085,79.736,4.651,0.432,77.776,75.051,80.795,5.744
Tekirdağ,77.582,74.932,80.428,5.495,0.192,77.774,75.006,80.768,5.762
Yozgat,77.481,74.746,80.294,5.548,0.244,77.726,74.849,80.737,5.888
Adana,77.528,74.703,80.376,5.673,0.131,77.659,74.910,80.474,5.564
Hatay,77.930,75.735,80.165,4.430,-0.279,77.651,75.419,79.973,4.554
Uşak,78.106,75.915,80.308,4.392,-0.459,77.647,74.931,80.460,5.528
Ardahan,76.925,74.211,79.908,5.698,0.692,77.617,74.781,80.857,6.076
Erzurum,77.287,74.904,79.699,4.796,0.290,77.577,75.361,79.835,4.474
Şanlıurfa,77.735,74.602,80.713,6.110,-0.164,77.571,74.480,80.618,6.138
Kütahya,76.788,74.496,79.098,4.602,0.673,77.461,75.037,79.939,4.902
Manisa,77.097,74.389,79.898,5.508,0.273,77.370,74.529,80.350,5.821
Hakkari,77.123,74.133,80.004,5.871,0.046,77.168,74.270,80.068,5.798
Van,76.963,74.443,79.529,5.086,0.133,77.097,74.904,79.320,4.416
Afyonkarahisar,77.073,74.541,79.643,5.102,-0.113,76.959,74.277,79.727,5.449
Ağrı,76.773,74.248,79.350,5.102,0.003,76.776,74.107,79.648,5.541
Gaziantep,76.937,74.327,79.523,5.196,-0.558,76.379,73.795,79.031,5.236
Kilis,76.138,72.872,79.545,6.673,-0.046,76.092,73.466,78.831,5.365

<br />
<br />
<br />

In [9]:
dd_replacement = {
    'Türkiye'   : {'tr': ('Türkiye', ''), 'ru': ('Турция', ''), 'en': ('Turkey', '')},
    'Adana'     : {'tr': ('Adana', ''), 'ru': ('Адана́', 'Адана (ил)'), 'en': ('Adana', 'Adana Province')},
    'Adıyaman'  : {'tr': ('Adıyaman', ''), 'ru': ('Адыяма́н', 'Адыяман (ил)'), 'en': ('Adıyaman', 'Adıyaman Province')},
    'Afyonkarahisar': {'tr': ('Afyonkarahisar', ''), 'ru': ('Афьо́нкарахи́сар', 'Афьонкарахисар (ил)'), 'en': ('Afyonkarahisar', 'Afyonkarahisar Province')},
    'Aksaray'   : {'tr': ('Aksaray', ''), 'ru': ('Аксарай', 'Аксарай (ил)'), 'en': ('Aksaray', 'Aksaray Province')},
    'Amasya'    : {'tr': ('Amasya', ''), 'ru': ('Ама́сья', 'Амасья (ил)'), 'en': ('Amasya', 'Amasya Province')},
    'Ankara'    : {'tr': ('Ankara', ''), 'ru': ('Анкара́', 'Анкара (ил)'), 'en': ('Ankara', 'Ankara Province')},
    'Antalya'   : {'tr': ('Antalya', ''), 'ru': ('Антáлья', 'Анталья (ил)'), 'en': ('Antalya', 'Antalya Province')},
    'Ardahan'   : {'tr': ('Ardahan', ''), 'ru': ('Ардаха́н', 'Ардахан (ил)'), 'en': ('Ardahan', 'Ardahan Province')},
    'Artvin'    : {'tr': ('Artvin', ''), 'ru': ('Артви́н', 'Артвин (ил)'), 'en': ('Artvin', 'Artvin Province')},
    'Aydın'     : {'tr': ('Aydın', ''), 'ru': ('Айды́н', 'Айдын (ил)'), 'en': ('Aydın', 'Aydın Province')},
    'Ağrı'      : {'tr': ('Ağrı', ''), 'ru': ('Агры́', 'Агры (ил)'), 'en': ('Ağrı', 'Ağrı Province')},
    'Balıkesir' : {'tr': ('Balıkesir', ''), 'ru': ('Балыкеси́р', 'Балыкесир (ил)'), 'en': ('Balıkesir', 'Balıkesir Province')},
    'Bartın'    : {'tr': ('Bartın', ''), 'ru': ('Бартын', 'Бартын (ил)'), 'en': ('Bartın', 'Bartın Province')},
    'Batman'    : {'tr': ('Batman', ''), 'ru': ('Батма́н', 'Батман (ил)'), 'en': ('Batman', 'Batman Province')},
    'Bayburt'   : {'tr': ('Bayburt', ''), 'ru': ('Байбурт', 'Байбурт (ил)'), 'en': ('Bayburt', 'Bayburt Province')},
    'Bilecik'   : {'tr': ('Bilecik', ''), 'ru': ('Биледжи́к', 'Биледжик (ил)'), 'en': ('Bilecik', 'Bilecik Province')},
    'Bingöl'    : {'tr': ('Bingöl', ''), 'ru': ('Бингёль', 'Бингёль (ил)'), 'en': ('Bingöl', 'Bingöl Province')},
    'Bitlis'    : {'tr': ('Bitlis', ''), 'ru': ('Битли́с', 'Битлис (ил)'), 'en': ('Bitlis', 'Bitlis Province')},
    'Bolu'      : {'tr': ('Bolu', ''), 'ru': ('Болу', 'Болу (ил)'), 'en': ('Bolu', 'Bolu Province')},
    'Burdur'    : {'tr': ('Burdur', ''), 'ru': ('Бурдур', 'Бурдур (ил)'), 'en': ('Burdur', 'Burdur Province')},
    'Bursa'     : {'tr': ('Bursa', ''), 'ru': ('Бу́рса', 'Бурса (ил)'), 'en': ('Bursa', 'Bursa Province')},
    'Denizli'   : {'tr': ('Denizli', ''), 'ru': ('Денизли́', 'Денизли (ил)'), 'en': ('Denizli', 'Denizli Province')},
    'Diyarbakır': {'tr': ('Diyarbakır', ''), 'ru': ('Диярбакы́р', 'Диярбакыр (ил)'), 'en': ('Diyarbakır', 'Diyarbakır Province')},
    'Düzce'     : {'tr': ('Düzce', ''), 'ru': ('Дюздже', 'Дюздже (ил)'), 'en': ('Düzce', 'Düzce Province')},
    'Edirne'    : {'tr': ('Edirne', ''), 'ru': ('Эди́рне', 'Эдирне (ил)'), 'en': ('Edirne', 'Edirne Province')},
    'Elazığ'    : {'tr': ('Elazığ', ''), 'ru': ('Элязы́г', 'Элязыг (ил)'), 'en': ('Elazığ', 'Elazığ Province')},
    'Erzincan'  : {'tr': ('Erzincan', ''), 'ru': ('Эрзинджа́н', 'Эрзинджан (ил)'), 'en': ('Erzincan', 'Erzincan Province')},
    'Erzurum'   : {'tr': ('Erzurum', ''), 'ru': ('Эрзуру́м', 'Эрзурум (ил)'), 'en': ('Erzurum', 'Erzurum Province')},
    'Eskişehir' : {'tr': ('Eskişehir', ''), 'ru': ('Эскишехи́р', 'Эскишехир (ил)'), 'en': ('Eskişehir', 'Eskişehir Province')},
    'Gaziantep' : {'tr': ('Gaziantep', ''), 'ru': ('Газианте́п', 'Газиантеп (ил)'), 'en': ('Gaziantep', 'Gaziantep Province')},
    'Giresun'   : {'tr': ('Giresun', ''), 'ru': ('Гиресу́н', 'Гиресун (ил)'), 'en': ('Giresun', 'Giresun Province')},
    'Gümüşhane' : {'tr': ('Gümüşhane', ''), 'ru': ('Гюмюшхане́', 'Гюмюшхане (ил)'), 'en': ('Gümüşhane', 'Gümüşhane Province')},
    'Hakkari'   : {'tr': ('Hakkari', ''), 'ru': ('Хаккяри', 'Хаккяри (ил)'), 'en': ('Hakkâri', 'Hakkâri Province')},
    'Hatay'     : {'tr': ('Hatay', ''), 'ru': ('Хатай', 'Хатай (ил)'), 'en': ('Hatay', 'Hatay Province')},
    'Isparta'   : {'tr': ('Isparta', ''), 'ru': ('Ыспарта́', 'Ыспарта (ил)'), 'en': ('Isparta', 'Isparta Province')},
    'Iğdır'     : {'tr': ('Iğdır', ''), 'ru': ('Ыгды́р', 'Ыгдыр (ил)'), 'en': ('Iğdır', 'Iğdır Province')},
    'Kahramanmaraş': {'tr': ('Kahramanmaraş', ''), 'ru': ('Кахраманмара́ш', 'Кахраманмараш (ил)'), 'en': ('Kahramanmaraş', 'Kahramanmaraş Province')},
    'Karabük'   : {'tr': ('Karabük', ''), 'ru': ('Карабюк', 'Карабюк (ил)'), 'en': ('Karabük', 'Karabük Province')},
    'Karaman'   : {'tr': ('Karaman', ''), 'ru': ('Караман', 'Караман (ил)'), 'en': ('Karaman', 'Karaman Province')},
    'Kars'      : {'tr': ('Kars', ''), 'ru': ('Карс', 'Карс (ил)'), 'en': ('Kars', 'Kars Province')},
    'Kastamonu' : {'tr': ('Kastamonu', ''), 'ru': ('Кастамону́', 'Кастамону (ил)'), 'en': ('Kastamonu', 'Kastamonu Province')},
    'Kayseri'   : {'tr': ('Kayseri', ''), 'ru': ('Кайсери', 'Кайсери (ил)'), 'en': ('Kayseri', 'Kayseri Province')},
    'Kilis'     : {'tr': ('Kilis', ''), 'ru': ('Кили́с', 'Килис (ил)'), 'en': ('Kilis', 'Kilis Province')},
    'Kocaeli'   : {'tr': ('Kocaeli', ''), 'ru': ('Коджаэли́', 'Коджаэли (ил)'), 'en': ('Kocaeli', 'Kocaeli Province')},
    'Konya'     : {'tr': ('Konya', ''), 'ru': ('Ко́нья', 'Конья (ил)'), 'en': ('Konya', 'Konya Province')},
    'Kütahya'   : {'tr': ('Kütahya', ''), 'ru': ('Кюта́хья', 'Кютахья (ил)'), 'en': ('Kütahya', 'Kütahya Province')},
    'Kırklareli': {'tr': ('Kırklareli', ''), 'ru': ('Кыркларели́', 'Кыркларели (ил)'), 'en': ('Kırklareli', 'Kırklareli Province')},
    'Kırıkkale' : {'tr': ('Kırıkkale', ''), 'ru': ('Кыры́ккале́', 'Кырыккале (ил)'), 'en': ('Kırıkkale', 'Kırıkkale Province')},
    'Kırşehir'  : {'tr': ('Kırşehir', ''), 'ru': ('Кыршехир', 'Кыршехир (ил)'), 'en': ('Kırşehir', 'Kırşehir Province')},
    'Malatya'   : {'tr': ('Malatya', ''), 'ru': ('Мала́тья', 'Малатья (ил)'), 'en': ('Malatya', 'Malatya Province')},
    'Manisa'    : {'tr': ('Manisa', ''), 'ru': ('Мани́са', 'Маниса (ил)'), 'en': ('Manisa', 'Manisa Province')},
    'Mardin'    : {'tr': ('Mardin', ''), 'ru': ('Марди́н', 'Мардин (ил)'), 'en': ('Mardin', 'Mardin Province')},
    'Mersin'    : {'tr': ('Mersin', ''), 'ru': ('Мéрсин', 'Мерсин (ил)'), 'en': ('Mersin', 'Mersin Province')},
    'Muğla'     : {'tr': ('Muğla', ''), 'ru': ('Му́гла', 'Мугла (ил)'), 'en': ('Muğla', 'Muğla Province')},
    'Muş'       : {'tr': ('Muş', ''), 'ru': ('Муш', 'Муш (ил)'), 'en': ('Muş', 'Muş Province')},
    'Nevşehir'  : {'tr': ('Nevşehir', ''), 'ru': ('Невшехир', 'Невшехир (ил)'), 'en': ('Nevşehir', 'Nevşehir Province')},
    'Niğde'     : {'tr': ('Niğde', ''), 'ru': ('Ни́где', 'Нигде (ил)'), 'en': ('Niğde', 'Niğde Province')},
    'Ordu'      : {'tr': ('Ordu', ''), 'ru': ('Орду́', 'Орду (ил)'), 'en': ('Ordu', 'Ordu Province')},
    'Osmaniye'  : {'tr': ('Osmaniye', ''), 'ru': ('Османие́', 'Османие (ил)'), 'en': ('Osmaniye', 'Osmaniye Province')},
    'Rize'      : {'tr': ('Rize', ''), 'ru': ('Ризе', 'Ризе (ил)'), 'en': ('Rize', 'Rize Province')},
    'Sakarya'   : {'tr': ('Sakarya', ''), 'ru': ('Сака́рья', 'Сакарья (ил)'), 'en': ('Sakarya', 'Sakarya Province')},
    'Samsun'    : {'tr': ('Samsun', ''), 'ru': ('Самсу́н', 'Самсун (ил)'), 'en': ('Samsun', 'Samsun Province')},
    'Siirt'     : {'tr': ('Siirt', ''), 'ru': ('Сии́рт', 'Сиирт (ил)'), 'en': ('Siirt', 'Siirt Province')},
    'Sinop'     : {'tr': ('Sinop', ''), 'ru': ('Сино́п', 'Синоп (ил)'), 'en': ('Sinop', 'Sinop Province')},
    'Sivas'     : {'tr': ('Sivas', ''), 'ru': ('Сива́с', 'Сивас (ил)'), 'en': ('Sivas', 'Sivas Province')},
    'Tekirdağ'  : {'tr': ('Tekirdağ', ''), 'ru': ('Текирда́г', 'Текирдаг (ил)'), 'en': ('Tekirdağ', 'Tekirdağ Province')},
    'Tokat'     : {'tr': ('Tokat', ''), 'ru': ('Тока́т', 'Токат (ил)'), 'en': ('Tokat', 'Tokat Province')},
    'Trabzon'   : {'tr': ('Trabzon', ''), 'ru': ('Трабзо́н', 'Трабзон (ил)'), 'en': ('Trabzon', 'Trabzon Province')},
    'Tunceli'   : {'tr': ('Tunceli', ''), 'ru': ('Ту́нджели', 'Тунджели (ил)'), 'en': ('Tunceli', 'Tunceli Province')},
    'Uşak'      : {'tr': ('Uşak', ''), 'ru': ('У́шак', 'Ушак (ил)'), 'en': ('Uşak', 'Uşak Province')},
    'Van'       : {'tr': ('Van', ''), 'ru': ('Ван', 'Ван (ил)'), 'en': ('Van', 'Van Province')},
    'Yalova'    : {'tr': ('Yalova', ''), 'ru': ('Ялова', 'Ялова (ил)'), 'en': ('Yalova', 'Yalova Province')},
    'Yozgat'    : {'tr': ('Yozgat', ''), 'ru': ('Йозгат', 'Йозгат (ил)'), 'en': ('Yozgat', 'Yozgat Province')},
    'Zonguldak' : {'tr': ('Zonguldak', ''), 'ru': ('Зонгулда́к', 'Зонгулдак (ил)'), 'en': ('Zonguldak', 'Zonguldak Province')},
    'Çanakkale' : {'tr': ('Çanakkale', ''), 'ru': ('Чанаккале́', 'Чанаккале (ил)'), 'en': ('Çanakkale', 'Çanakkale Province')},
    'Çankırı'   : {'tr': ('Çankırı', ''), 'ru': ('Чанкыры', 'Чанкыры (ил)'), 'en': ('Çankırı', 'Çankırı Province')},
    'Çorum'     : {'tr': ('Çorum', ''), 'ru': ('Чору́м', 'Чорум (ил)'), 'en': ('Çorum', 'Çorum Province')},
    'İstanbul'  : {'tr': ('İstanbul', ''), 'ru': ('Стамбу́л', 'Стамбул (ил)'), 'en': ('Istanbul', 'Istanbul Province')},
    'İzmir'     : {'tr': ('İzmir', ''), 'ru': ('Изми́р', 'Измир (ил)'), 'en': ('İzmir', 'İzmir Province')},
    'Şanlıurfa' : {'tr': ('Şanlıurfa', ''), 'ru': ('Шанлыу́рфа', 'Шанлыурфа (ил)'), 'en': ('Şanlıurfa', 'Şanlıurfa Province')},
    'Şırnak'    : {'tr': ('Şırnak', ''), 'ru': ('Ширнак', 'Ширнак (ил)'), 'en': ('Şırnak', 'Şırnak Province')},
}

In [13]:
# create code for placing info in Wikipedia
def create_table(df, file_header, file_footer, lang='ru'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=2, *, add_par=''):  # change_value
        return 'style="padding-right:1em;"|—' if math.isnan(x) else \
               f'style="padding-right:1em;color:darkgreen;{add_par}"|{x:0.{prec}f}' if x>0 else \
               f'style="padding-right:1em;color:crimson;{add_par}"|−{-x:0.{prec}f}' if x<0 else \
               f'style="padding-right:1em;color:darkgray;{add_par}"|−{x:0.{prec}f}'  # normal sorting is required '−' before 0.0 - bug in wiki

    def chval_bold(x, prec=2, *, add_par=''):  # change_value
        return '—' if math.isnan(x) else \
               f'style="padding-right:1em;color:darkgreen;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="padding-right:1em;color:crimson;{add_par}"|\'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:1em;color:darkgray;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\''                 #  background:#fffae0;
    
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()
    
    with open('design/' + file_footer, mode='r', encoding="utf-8") as fh:
        table_footer = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name == 'Türkiye':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:left;"|\'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                    f'|| style="text-align:center; background:#e0ffd8;"|\'\'\'{if_value(ser["past_overall"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|\'\'\'{if_value(ser["past_male"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|\'\'\'{if_value(ser["past_female"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fff8dc;"|\'\'\'{if_value(ser["past_f-m"], 2)}\'\'\' ' + \
                  f'|| {chval_bold(ser["Δ_years"], 2, add_par="border-left-width:2px;")} ' + \
                  f'|| style="text-align:center;background:#e0ffd8;border-left-width:2px;"|\'\'\'{if_value(ser["overall"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|\'\'\'{if_value(ser["male"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|\'\'\'{if_value(ser["female"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fff8dc;"|\'\'\'{if_value(ser["f-m"], 2)}\'\'\' '
        else:        
            st += '\n' + '|-\n' + \
                  f'|style="text-align:left;"|[[{dd_replacement[ser.name][lang][1]}|{dd_replacement[ser.name][lang][0]}]] ' + \
                  f'|| style="text-align:center; background:#e0ffd8;"|\'\'\'{if_value(ser["past_overall"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|{if_value(ser["past_male"], 2)} ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|{if_value(ser["past_female"], 2)} ' + \
                  f'|| style="text-align:center;background:#fff8dc;"|{if_value(ser["past_f-m"], 2)} ' + \
                  f'|| {chval(ser["Δ_years"], 2, add_par="border-left-width:2px;")} ' + \
                  f'|| style="text-align:center;background:#e0ffd8;border-left-width:2px;"|\'\'\'{if_value(ser["overall"], 2)}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|{if_value(ser["male"], 2)} ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|{if_value(ser["female"], 2)} ' + \
                  f'|| style="text-align:center;background:#fff8dc;"|{if_value(ser["f-m"], 2)} '
            
    if lang == 'ru':
        st = re.sub('(?<=\d)\.(?=\d)', ',', st)  # replace . to comma, if this . is between two digits

    st = table_header + st + '\n' + table_footer
    
    # gray color for missing values
    st = st.replace(';"|—', ';color:silver;"|—')

    return st


table_code = create_table(df, file_header='turkstat_header_ru.txt', file_footer='turkstat_footer_ru.txt', lang='ru')

# # write the code to file
with open('output/Table code for Turkish regions -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [15]:
table_code = create_table(df, file_header='turkstat_header_en.txt', file_footer='turkstat_footer_en.txt', lang='en')

# write the code to file
with open('output/Table code for Turkish regions -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br>
<br>
<br>
<hr>

The further code allows to create table for manual coloring of map at [MapChart.net](https://www.mapchart.net/turkiye.html)

In [12]:
assert False

AssertionError:

In [ ]:
df.head()

In [ ]:
df_coloring = df.loc[:, ['overall', 'past_overall']] \
                .round(2)
df_coloring.head()

In [ ]:
df_coloring.sort_index(inplace=True)
indexes = df_coloring.index.to_list()
ls_change_order = ['Türkiye']    # 'İstanbul'
indexes = list(el for el in indexes if el not in ls_change_order)
indexes = ls_change_order + indexes
df_coloring = df_coloring.reindex(indexes)
df_coloring.head()

In [ ]:
define_color = lambda v: ('#005203' if v >= 81 else
                          '#3faf46' if v >= 80 else
                          '#81d41a' if v >= 79 else
                          '#ffd428' if v >= 78 else
                          '#ff972f' if v >= 77 else
                          '#ff0000' if v >= 76 else
                          '#c40000')

In [ ]:
df_coloring.insert(loc=1, column='color_1', value=df['overall'].map(define_color))
df_coloring.insert(loc=3, column='color_2', value=df['past_overall'].map(define_color))
df_coloring.head()

In [ ]:
df_coloring.to_csv('output/coloring of Turkish provinces.csv')