[List of Mexican states by life expectancy](https://en.wikipedia.org/wiki/List_of_Mexican_states_by_life_expectancy) / [Продолжительность жизни в штатах Мексики](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_штатах_Мексики)<br />
[Administrative divisions of Mexico](https://en.wikipedia.org/wiki/Administrative_divisions_of_Mexico) / 
[Административное деление Мексики](https://ru.wikipedia.org/wiki/Административное_деление_Мексики)<br />
source of data: [INEGI](https://www.inegi.org.mx/app/tabulados/interactivos/?pxq=Mortalidad_Mortalidad_09_b87a4bf1-9b47-442a-a5fc-ee5c65e37648)

In [2]:
import pandas as pd
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [3]:
# pd.options.display.min_rows = 4
# pd.options.display.max_rows = 50

In [4]:
df = pd.read_excel('data/Mortalidad_09.xlsx', sheet_name='Tabulado', skiprows=8, skipfooter=11,
                   header=None, index_col=0) # skiprows=4, header=None, index_col=0)
df.index.name = ''

df.dropna(how='all', inplace=True)

df.rename(index = {'Estados Unidos Mexicanos': '=MÉXICO=',
                   'Ciudad de México': 'Mexico City',
                   'Coahuila de Zaragoza': 'Coahuila',
                   'Michoacán de Ocampo': 'Michoacán',
                   'México': 'State of México',
                   'Veracruz de Ignacio de la Llave': 'Veracruz'}, inplace=True)

print(df.shape)
df.head(3)

(33, 51)

,1,2,3,4,5,6,7,8,9,10,...,42,43,44,45,46,47,48,49,50,51
,,,,,,,,,,,,,,,,,,,,,
=MÉXICO=,74.3,71.4,77.2,74.7,71.8,77.7,74.9,72.0,77.8,75.2,...,78.6,75.5,72.4,78.9,75.7,72.6,79.0,75.9,72.7,79.2
Aguascalientes,75.7,72.7,78.6,76.0,73.0,78.9,76.1,73.2,78.9,76.4,...,79.9,76.8,73.8,80.1,77.0,74.0,80.3,77.2,74.2,80.5
Baja California,75.0,72.2,78.0,75.4,72.6,78.4,75.4,72.7,78.4,75.7,...,79.6,76.6,73.6,79.8,76.7,73.8,80.0,76.9,73.9,80.1

In [5]:
ls_cols = []
for year in list(range(2010, 2026+1)):
    ls_cols.extend([f'{year}_t', f'{year}_m', f'{year}_f'])

df.columns = ls_cols
df.head(3)

,2010_t,2010_m,2010_f,2011_t,2011_m,2011_f,2012_t,2012_m,2012_f,2013_t,...,2023_f,2024_t,2024_m,2024_f,2025_t,2025_m,2025_f,2026_t,2026_m,2026_f
,,,,,,,,,,,,,,,,,,,,,
=MÉXICO=,74.3,71.4,77.2,74.7,71.8,77.7,74.9,72.0,77.8,75.2,...,78.6,75.5,72.4,78.9,75.7,72.6,79.0,75.9,72.7,79.2
Aguascalientes,75.7,72.7,78.6,76.0,73.0,78.9,76.1,73.2,78.9,76.4,...,79.9,76.8,73.8,80.1,77.0,74.0,80.3,77.2,74.2,80.5
Baja California,75.0,72.2,78.0,75.4,72.6,78.4,75.4,72.7,78.4,75.7,...,79.6,76.6,73.6,79.8,76.7,73.8,80.0,76.9,73.9,80.1

In [6]:
def sort_df(df, by=['2025_t', '2025_m', '2025_f'], ascending=False):
    df.sort_values(by=by, ascending=ascending, inplace=True)
    indexes = df.index.to_list()
    ls_change_order = ['=MÉXICO=']
    indexes = list(el for el in indexes if el not in ls_change_order)
    indexes = ls_change_order + indexes
    return df.reindex(indexes)

df = sort_df(df)
df.head(3)

,2010_t,2010_m,2010_f,2011_t,2011_m,2011_f,2012_t,2012_m,2012_f,2013_t,...,2023_f,2024_t,2024_m,2024_f,2025_t,2025_m,2025_f,2026_t,2026_m,2026_f
,,,,,,,,,,,,,,,,,,,,,
=MÉXICO=,74.3,71.4,77.2,74.7,71.8,77.7,74.9,72.0,77.8,75.2,...,78.6,75.5,72.4,78.9,75.7,72.6,79.0,75.9,72.7,79.2
Nuevo León,77.4,74.6,80.3,77.6,74.7,80.5,77.5,74.7,80.4,77.8,...,80.7,77.7,74.8,80.9,77.9,74.9,81.1,78.1,75.1,81.3
Baja California Sur,76.2,73.5,79.2,76.5,73.7,79.5,76.6,73.8,79.7,76.9,...,80.1,77.2,74.3,80.3,77.3,74.4,80.5,77.5,74.6,80.7

<br>
<br>

In [8]:
df[[f'{year}_t' for year in range(2010, 2026+1)]].head(3)

,2010_t,2011_t,2012_t,2013_t,2014_t,2015_t,2016_t,2017_t,2018_t,2019_t,2020_t,2021_t,2022_t,2023_t,2024_t,2025_t,2026_t
,,,,,,,,,,,,,,,,,
=MÉXICO=,74.3,74.7,74.9,75.2,75.1,75.1,74.8,74.8,74.9,74.8,68.9,68.8,75.2,75.3,75.5,75.7,75.9
Nuevo León,77.4,77.6,77.5,77.8,77.9,77.9,77.8,78.0,77.4,77.3,71.6,71.1,77.4,77.6,77.7,77.9,78.1
Baja California Sur,76.2,76.5,76.6,76.9,76.3,76.3,76.2,76.4,76.8,76.7,72.5,69.6,76.8,77.0,77.2,77.3,77.5

In [9]:
# just for interest, look at estimation
df_estimation = df[['2013_t', '2019_t', '2020_t', '2021_t', '2022_t', '2023_t', '2024_t', '2025_t', '2025_m', '2025_f', '2026_t', '2026_m', '2026_f']]
df_estimation.head(3)

,2013_t,2019_t,2020_t,2021_t,2022_t,2023_t,2024_t,2025_t,2025_m,2025_f,2026_t,2026_m,2026_f
,,,,,,,,,,,,,
=MÉXICO=,75.2,74.8,68.9,68.8,75.2,75.3,75.5,75.7,72.6,79.0,75.9,72.7,79.2
Nuevo León,77.8,77.3,71.6,71.1,77.4,77.6,77.7,77.9,74.9,81.1,78.1,75.1,81.3
Baja California Sur,76.9,76.7,72.5,69.6,76.8,77.0,77.2,77.3,74.4,80.5,77.5,74.6,80.7

In [10]:
df = df[['2013_t', '2019_t', '2020_t', '2021_t', '2022_t', '2023_t', '2024_t', '2025_t', '2025_m', '2025_f']]
df.head(3)

,2013_t,2019_t,2020_t,2021_t,2022_t,2023_t,2024_t,2025_t,2025_m,2025_f
,,,,,,,,,,
=MÉXICO=,75.2,74.8,68.9,68.8,75.2,75.3,75.5,75.7,72.6,79.0
Nuevo León,77.8,77.3,71.6,71.1,77.4,77.6,77.7,77.9,74.9,81.1
Baja California Sur,76.9,76.7,72.5,69.6,76.8,77.0,77.2,77.3,74.4,80.5

In [11]:
def extend_df(df, prec=1):
    df.insert(loc=1, column='2013→2019', value=(df['2019_t']-df['2013_t']).round(prec))
    df.insert(loc=3, column='2019→2020', value=(df['2020_t']-df['2019_t']).round(prec))
    df.insert(loc=5, column='2020→2021', value=(df['2021_t']-df['2020_t']).round(prec))
    df.insert(loc=7, column='2021→2022', value=(df['2022_t']-df['2021_t']).round(prec))
    df.insert(loc=9, column='2022→2023', value=(df['2023_t']-df['2022_t']).round(prec))
    df.insert(loc=11, column='2023→2024', value=(df['2024_t']-df['2023_t']).round(prec))
    df.insert(loc=13, column='2024→2025', value=(df['2025_t']-df['2024_t']).round(prec))
    df.insert(loc=15, column='2019→2025', value=(df['2025_t']-df['2019_t']).round(prec))
    df.insert(loc=16, column='2013→2025', value=(df['2025_t']-df['2013_t']).round(prec))
    df['2025_fΔm']  = (df['2025_f']-df['2025_m']).round(prec)
    
    return df
    
df = extend_df(df)
df

,2013_t,2013→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2024_t,2024→2025,2025_t,2019→2025,2013→2025,2025_m,2025_f,2025_fΔm
,,,,,,,,,,,,,,,,,,,,
=MÉXICO=,75.2,-0.4,74.8,-5.9,68.9,-0.1,68.8,6.4,75.2,0.1,75.3,0.2,75.5,0.2,75.7,0.9,0.5,72.6,79.0,6.4
Nuevo León,77.8,-0.5,77.3,-5.7,71.6,-0.5,71.1,6.3,77.4,0.2,77.6,0.1,77.7,0.2,77.9,0.6,0.1,74.9,81.1,6.2
Baja California Sur,76.9,-0.2,76.7,-4.2,72.5,-2.9,69.6,7.2,76.8,0.2,77.0,0.2,77.2,0.1,77.3,0.6,0.4,74.4,80.5,6.1
Coahuila,77.2,-0.5,76.7,-6.8,69.9,2.9,72.8,4.0,76.8,0.1,76.9,0.2,77.1,0.1,77.2,0.5,0.0,74.3,80.5,6.2
Aguascalientes,76.4,0.1,76.5,-6.4,70.1,1.3,71.4,5.1,76.5,0.2,76.7,0.1,76.8,0.2,77.0,0.5,0.6,74.0,80.3,6.3
Mexico City,77.0,-0.5,76.5,-7.3,69.2,1.1,70.3,6.2,76.5,0.1,76.6,0.2,76.8,0.2,77.0,0.5,0.0,74.0,80.2,6.2
Sonora,76.5,-0.2,76.3,-6.4,69.9,1.2,71.1,5.3,76.4,0.2,76.6,0.2,76.8,0.1,76.9,0.6,0.4,74.0,80.1,6.1
Chihuahua,76.1,0.1,76.2,-6.7,69.5,2.9,72.4,3.9,76.3,0.1,76.4,0.2,76.6,0.2,76.8,0.6,0.7,73.8,80.0,6.2
Baja California,75.7,0.4,76.1,-7.2,68.9,2.3,71.2,5.0,76.2,0.2,76.4,0.2,76.6,0.1,76.7,0.6,1.0,73.8,80.0,6.2
Querétaro,75.8,0.1,75.9,-5.5,70.4,-2.6,67.8,8.1,75.9,0.2,76.1,0.2,76.3,0.1,76.4,0.5,0.6,73.4,79.7,6.3
Colima,76.2,-0.5,75.7,-3.6,72.1,-2.4,69.7,6.1,75.8,0.2,76.0,0.2,76.2,0.1,76.3,0.6,0.1,73.3,79.6,6.3
Sinaloa,75.7,0.0,75.7,-5.5,70.2,0.9,71.1,4.7,75.8,0.1,75.9,0.2,76.1,0.2,76.3,0.6,0.6,73.3,79.5,6.2
Jalisco,75.7,-0.1,75.6,-4.4,71.2,-1.8,69.4,6.3,75.7,0.1,75.8,0.2,76.0,0.2,76.2,0.6,0.5,73.2,79.5,6.3
Quintana Roo,75.9,-0.4,75.5,-6.9,68.6,-0.3,68.3,7.3,75.6,0.2,75.8,0.2,76.0,0.2,76.2,0.7,0.3,73.2,79.4,6.2
Tamaulipas,76.0,-0.5,75.5,-5.0,70.5,2.0,72.5,3.0,75.5,0.2,75.7,0.2,75.9,0.1,76.0,0.5,0.0,73.0,79.3,6.3
Nayarit,75.0,0.2,75.2,-3.6,71.6,-1.5,70.1,5.2,75.3,0.1,75.4,0.2,75.6,0.2,75.8,0.6,0.8,72.7,79.1,6.4
Durango,74.8,0.3,75.1,-5.3,69.8,1.2,71.0,4.2,75.2,0.1,75.3,0.2,75.5,0.2,75.7,0.6,0.9,72.7,79.0,6.3
San Luis Potosí,75.0,-0.1,74.9,-6.5,68.4,-0.4,68.0,6.9,74.9,0.2,75.1,0.2,75.3,0.2,75.5,0.6,0.5,72.4,78.8,6.4
State of México,74.9,-0.2,74.7,-8.0,66.7,0.1,66.8,7.9,74.7,0.2,74.9,0.2,75.1,0.2,75.3,0.6,0.4,72.3,78.6,6.3
Yucatán,74.9,-0.3,74.6,-3.9,70.7,-1.3,69.4,5.2,74.6,0.2,74.8,0.2,75.0,0.2,75.2,0.6,0.3,72.1,78.5,6.4
Guanajuato,75.0,-0.4,74.6,-6.3,68.3,-0.7,67.6,6.9,74.5,0.2,74.7,0.2,74.9,0.2,75.1,0.5,0.1,72.0,78.4,6.4
Campeche,75.4,-1.3,74.1,-6.1,68.0,0.2,68.2,5.9,74.1,0.2,74.3,0.2,74.5,0.2,74.7,0.6,-0.7,71.6,78.1,6.5
Zacatecas,75.0,-1.0,74.0,-6.3,67.7,-0.7,67.0,7.0,74.0,0.2,74.2,0.2,74.4,0.2,74.6,0.6,-0.4,71.4,78.0,6.6
Morelos,75.0,-1.0,74.0,-5.6,68.4,-2.3,66.1,7.8,73.9,0.2,74.1,0.2,74.3,0.2,74.5,0.5,-0.5,71.4,77.9,6.5
Tlaxcala,74.2,-0.4,73.8,-8.6,65.2,0.0,65.2,8.6,73.8,0.2,74.0,0.2,74.2,0.2,74.4,0.6,0.2,71.3,77.8,6.5
Michoacán,74.0,-0.2,73.8,-4.4,69.4,-2.9,66.5,7.2,73.7,0.2,73.9,0.2,74.1,0.2,74.3,0.5,0.3,71.2,77.7,6.5
Hidalgo,74.4,-0.9,73.5,-5.3,68.2,-1.1,67.1,6.4,73.5,0.2,73.7,0.2,73.9,0.2,74.1,0.6,-0.3,71.0,77.5,6.5
Puebla,73.8,-0.2,73.6,-6.3,67.3,-2.0,65.3,8.2,73.5,0.2,73.7,0.2,73.9,0.2,74.1,0.5,0.3,71.0,77.5,6.5
Tabasco,74.3,-0.9,73.4,-6.4,67.0,2.2,69.2,4.2,73.4,0.2,73.6,0.2,73.8,0.2,74.0,0.6,-0.3,70.9,77.4,6.5
Veracruz,74.3,-0.9,73.4,-4.1,69.3,-0.4,68.9,4.4,73.3,0.2,73.5,0.2,73.7,0.2,73.9,0.5,-0.4,70.8,77.3,6.5
Oaxaca,73.9,-0.9,73.0,-4.2,68.8,-1.9,66.9,6.0,72.9,0.2,73.1,0.2,73.3,0.2,73.5,0.5,-0.4,70.3,77.0,6.7
Guerrero,73.3,-0.5,72.8,-3.7,69.1,0.3,69.4,3.3,72.7,0.2,72.9,0.2,73.1,0.2,73.3,0.5,0.0,70.2,76.8,6.6
Chiapas,73.3,-0.7,72.6,-4.7,67.9,-0.2,67.7,4.9,72.6,0.2,72.8,0.2,73.0,0.2,73.2,0.6,-0.1,70.0,76.6,6.6

In [12]:
mal.min_and_max_values(df.loc[:, '2013_t':'2013→2025'].drop(columns=['2021→2022', '2022_t', '2022→2023']),
                       row_center=['Mexico City', '=MÉXICO='], max_lng=7)

Number of records: 33

<br />
<br />

In [14]:
# for name in sorted(df.index.to_list()):
#     print(f'    "{name}"   : {{"es": ("", ""), "en": ("", ""), "ru": ("", "")}},')

In [15]:
dd_replacement_regions = {
    "=MÉXICO="   : {"es": ("MÉXICO", ""), "en": ("Mexico on average", ""), "ru": ("Мексика в среднем", "")},
    "Aguascalientes"   : {"es": ("Aguascalientes", "Aguascalientes"), "en": ("Aguascalientes", "Aguascalientes"), "ru": ("Агуаскалье́нтес", "Агуаскальентес (штат)")},
    "Baja California"   : {"es": ("Baja California", "Baja California"), "en": ("Baja California", "Baja California"), "ru": ("Нижняя Калифо́рния", "Нижняя Калифорния")},
    "Baja California Sur"   : {"es": ("Baja California Sur", "Baja California Sur"), "en": ("Baja California Sur", "Baja California Sur"), "ru": ("Южная Нижняя Калифо́рния", "Южная Нижняя Калифорния")},
    "Campeche"   : {"es": ("Campeche", "Campeche"), "en": ("Campeche", "Campeche"), "ru": ("Кампе́че", "Кампече (штат)")},
    "Chiapas"   : {"es": ("Chiapas", "Chiapas"), "en": ("Chiapas", "Chiapas"), "ru": ("Чья́пас", "Чьяпас")},
    "Chihuahua"   : {"es": ("Chihuahua", "Chihuahua"), "en": ("Chihuahua", "Chihuahua (state)"), "ru": ("Чиуа́уа", "Чиуауа")},
    "Mexico City"   : {"es": ("Ciudad de México", "Ciudad de México"), "en": ("Mexico City", "Mexico City"), "ru": ("Ме́хико", "Мехико")},
    "Coahuila"   : {"es": ("Coahuila", "Coahuila"), "en": ("Coahuila", "Coahuila"), "ru": ("Коауила", "Коауила")},
    "Colima"   : {"es": ("Colima", "Colima"), "en": ("Colima", "Colima"), "ru": ("Коли́ма", "Колима (штат)")},
    "Durango"   : {"es": ("Durango", "Durango"), "en": ("Durango", "Durango"), "ru": ("Дура́нго", "Дуранго (штат)")},
    "Guanajuato"   : {"es": ("Guanajuato", "Guanajuato"), "en": ("Guanajuato", "Guanajuato"), "ru": ("Гуанахуа́то", "Гуанахуато (штат)")},
    "Guerrero"   : {"es": ("Guerrero", "Estado de Guerrero"), "en": ("Guerrero", "Guerrero"), "ru": ("Герре́ро", "Герреро")},
    "Hidalgo"   : {"es": ("Hidalgo", "Estado de Hidalgo"), "en": ("Hidalgo", "Hidalgo (state)"), "ru": ("Ида́льго", "Идальго (штат)")},
    "Jalisco"   : {"es": ("Jalisco", "Jalisco"), "en": ("Jalisco", "Jalisco"), "ru": ("Хали́ско", "Халиско")},
    "Michoacán"   : {"es": ("Michoacán", "Michoacán"), "en": ("Michoacán", "Michoacán"), "ru": ("Мичоака́н", "Мичоакан")},
    "Morelos"   : {"es": ("Morelos", "Morelos"), "en": ("Morelos", "Morelos"), "ru": ("Морелос", "Морелос")},
    "State of México"   : {"es": ("Estado de México", "Estado de México"), "en": ("Mexico (state)", "State of Mexico"), "ru": ("Ме́хико (штат)", "Мехико (штат)")},
    "Nayarit"   : {"es": ("Nayarit", "Nayarit"), "en": ("Nayarit", "Nayarit"), "ru": ("Наяри́т", "Наярит")},
    "Nuevo León"   : {"es": ("Nuevo León", "Nuevo León"), "en": ("Nuevo León", "Nuevo León"), "ru": ("Нуэво-Леон", "Нуэво-Леон")},
    "Oaxaca"   : {"es": ("Oaxaca", "Oaxaca"), "en": ("Oaxaca", "Oaxaca"), "ru": ("Оаха́ка", "Оахака (штат)")},
    "Puebla"   : {"es": ("Puebla", "Puebla"), "en": ("Puebla", "Puebla"), "ru": ("Пуэ́бла", "Пуэбла")},
    "Querétaro"   : {"es": ("Querétaro", "Querétaro"), "en": ("Querétaro", "Querétaro"), "ru": ("Кере́таро", "Керетаро")},
    "Quintana Roo"   : {"es": ("Quintana Roo", "Quintana Roo"), "en": ("Quintana Roo", "Quintana Roo"), "ru": ("Кинта́на-Ро́о", "Кинтана-Роо")},
    "San Luis Potosí"   : {"es": ("San Luis Potosí", "San Luis Potosí"), "en": ("San Luis Potosí", "San Luis Potosí"), "ru": ("Сан-Луи́с-Потоси́", "Сан-Луис-Потоси (штат)")},
    "Sinaloa"   : {"es": ("Sinaloa", "Sinaloa"), "en": ("Sinaloa", "Sinaloa"), "ru": ("Синало́а", "Синалоа (штат)")},
    "Sonora"   : {"es": ("Sonora", "Sonora"), "en": ("Sonora", "Sonora"), "ru": ("Соно́ра", "Сонора")},
    "Tabasco"   : {"es": ("Tabasco", "Tabasco"), "en": ("Tabasco", "Tabasco"), "ru": ("Таба́ско", "Табаско")},
    "Tamaulipas"   : {"es": ("Tamaulipas", "Tamaulipas"), "en": ("Tamaulipas", "Tamaulipas"), "ru": ("Тамаули́пас", "Тамаулипас")},
    "Tlaxcala"   : {"es": ("Tlaxcala", "Tlaxcala"), "en": ("Tlaxcala", "Tlaxcala"), "ru": ("Тласка́ла", "Тласкала (штат)")},
    "Veracruz"   : {"es": ("Veracruz", "Estado de Veracruz"), "en": ("Veracruz", "Veracruz"), "ru": ("Веракру́с", "Веракрус (штат)")},
    "Yucatán"   : {"es": ("Yucatán", "Yucatán"), "en": ("Yucatán", "Yucatán"), "ru": ("Юката́н", "Юкатан (штат)")},
    "Zacatecas"   : {"es": ("Zacatecas", "Zacatecas"), "en": ("Zacatecas", "Zacatecas"), "ru": ("Сакатéкас", "Сакатекас (штат)")}
}

In [16]:
# create code for placing info in Wikipedia
def create_table_regions_v1(df, file_header, lang='ru'):

    def if_value(x, prec=1):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=1, *, add_par=''):  # change_value
        return f'padding-right:1.5ex;{add_par}"| —' if math.isnan(x) else \
               f'padding-right:1.5ex;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'padding-right:1.5ex;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'padding-right:1.5ex;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=1, *, add_par=''):  # change_value
        return f'padding-right:1.5ex;{add_par}"| \'\'\'—\'\'\'' if math.isnan(x) else \
               f'padding-right:1.5ex;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'padding-right:1.5ex;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]    
        if ser.name == '=MÉXICO=':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement_regions[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2025_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2025_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2025_fΔm"])}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-left:2ex;"| \'\'\'{if_value(ser["2013_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2013→2019"])} ' + \
                  f'|| \'\'\'{if_value(ser["2019_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"])} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"])} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"])} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"])} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"])} ' + \
                  f'|| \'\'\'{if_value(ser["2024_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2024→2025"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2025"])} ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2013→2025"])}'

        else:
            name_link = dd_replacement_regions[ser.name][lang][1]
            name_visible = dd_replacement_regions[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2025_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2025_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2025_fΔm"])} ' + \
                  f'||style="border-left-width:2px;padding-left:2ex;"| {if_value(ser["2013_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2013→2019"])} ' + \
                  f'|| {if_value(ser["2019_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"])} ' + \
                  f'|| {if_value(ser["2020_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"])} ' + \
                  f'|| {if_value(ser["2021_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"])} ' + \
                  f'|| {if_value(ser["2022_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"])} ' + \
                  f'|| {if_value(ser["2023_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"])} ' + \
                  f'|| {if_value(ser["2024_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2024→2025"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2025"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2013→2025"])}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —')

    return st


table_code = create_table_regions_v1(df, file_header='Mexican_states_header_ru -2025 -v1.txt', lang='ru')

# write the code to file
with open('output/Table code for Mexican states -v1 -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [17]:
table_code = create_table_regions_v1(df, file_header='Mexican_states_header_en -2025 -v1.txt', lang='en')

# write the code to file
with open('output/Table code for Mexican states -v1 -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br>
<br>

In [19]:
# alternative design of the table
def create_table_regions_v2(df, file_header, lang='ru'):

    def if_value(x, prec=1):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=1, *, add_par=''):  # change_value
        return f'padding-right:1.5ex;{add_par}"| —' if math.isnan(x) else \
               f'padding-right:1.5ex;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'padding-right:1.5ex;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'padding-right:1.5ex;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=1, *, add_par=''):  # change_value
        return f'padding-right:1.5ex;{add_par}"| \'\'\'—\'\'\'' if math.isnan(x) else \
               f'padding-right:1.5ex;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'padding-right:1.5ex;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]    
        if ser.name == '=MÉXICO=':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement_regions[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2025_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2025_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2025_fΔm"])}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-left:2ex;"| \'\'\'{if_value(ser["2019_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"])} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"])} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"])} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"])} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"])} ' + \
                  f'|| \'\'\'{if_value(ser["2024_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2024→2025"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2025"])}'

        else:
            name_link = dd_replacement_regions[ser.name][lang][1]
            name_visible = dd_replacement_regions[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2025_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2025_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2025_fΔm"])} ' + \
                  f'||style="border-left-width:2px;padding-left:2ex;"| {if_value(ser["2019_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"])} ' + \
                  f'|| {if_value(ser["2020_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"])} ' + \
                  f'|| {if_value(ser["2021_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"])} ' + \
                  f'|| {if_value(ser["2022_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"])} ' + \
                  f'|| {if_value(ser["2023_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"])} ' + \
                  f'|| {if_value(ser["2024_t"])} ' + \
                  f'||style="background:#fffae0;{chval(ser["2024→2025"])} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2025_t"])}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2025"])}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —')

    return st


table_code = create_table_regions_v2(df, file_header='Mexican_states_header_en -2025 -v2.txt', lang='en')

# write the code to file
with open('output/Table code for Mexican states -v2 -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)